-- MySQL Script generated by MySQL Workbench
-- Tue Feb  2 12:58:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`theatre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`theatre` (
  `id_theatre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `proprietaire` VARCHAR(45) NULL,
  PRIMARY KEY (`id_theatre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proprietaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proprietaire` (
  `id_proprietaire` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proprietaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`theatre_has_proprietaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`theatre_has_proprietaire` (
  `theatre_id_theatre` INT NOT NULL,
  `proprietaire_id_proprietaire` INT NOT NULL,
  PRIMARY KEY (`theatre_id_theatre`, `proprietaire_id_proprietaire`),
  INDEX `fk_theatre_has_proprietaire_proprietaire1_idx` (`proprietaire_id_proprietaire` ASC) VISIBLE,
  INDEX `fk_theatre_has_proprietaire_theatre_idx` (`theatre_id_theatre` ASC) VISIBLE,
  CONSTRAINT `fk_theatre_has_proprietaire_theatre`
    FOREIGN KEY (`theatre_id_theatre`)
    REFERENCES `mydb`.`theatre` (`id_theatre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_theatre_has_proprietaire_proprietaire1`
    FOREIGN KEY (`proprietaire_id_proprietaire`)
    REFERENCES `mydb`.`proprietaire` (`id_proprietaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`siege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`siege` (
  `id_siege` INT NOT NULL AUTO_INCREMENT,
  `num` VARCHAR(45) NULL,
  `theatre_id_theatre` INT NOT NULL,
  PRIMARY KEY (`id_siege`, `theatre_id_theatre`),
  INDEX `fk_siege_theatre1_idx` (`theatre_id_theatre` ASC) VISIBLE,
  CONSTRAINT `fk_siege_theatre1`
    FOREIGN KEY (`theatre_id_theatre`)
    REFERENCES `mydb`.`theatre` (`id_theatre`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cours` (
  `id_cours` INT NOT NULL AUTO_INCREMENT,
  `Moyenne` VARCHAR(45) NULL,
  `Adresse` VARCHAR(45) NULL,
  `Nom_professeur` VARCHAR(45) NULL,
  `Horaires` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cours`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filieres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filieres` (
  `id_filieres` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Nombre_de_classes` VARCHAR(45) NULL,
  `Nom_des_batiments` VARCHAR(45) NULL,
  PRIMARY KEY (`id_filieres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classes` (
  `id_classes` INT NOT NULL AUTO_INCREMENT,
  `Numero_classe` VARCHAR(45) NULL,
  `Moyenne_generale` VARCHAR(45) NULL,
  `Nombre_etudiants` VARCHAR(45) NULL,
  `Professeur_referent` VARCHAR(45) NULL,
  `Etudiant_delegue` VARCHAR(45) NULL,
  `filieres_id_filieres` INT NOT NULL,
  PRIMARY KEY (`id_classes`),
  INDEX `fk_classes_filieres1_idx` (`filieres_id_filieres` ASC) VISIBLE,
  CONSTRAINT `fk_classes_filieres1`
    FOREIGN KEY (`filieres_id_filieres`)
    REFERENCES `mydb`.`filieres` (`id_filieres`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employes` (
  `id_employes` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Profession` VARCHAR(45) NULL,
  `Salaire_net_mensuel` VARCHAR(45) NULL,
  `Adresse` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  `Numero_telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_employes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`campus` (
  `id_campus` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Adresse` VARCHAR(45) NULL,
  `Nombre_etudiants` VARCHAR(45) NULL,
  `Nombre_batiments` VARCHAR(45) NULL,
  PRIMARY KEY (`id_campus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etudiants` (
  `id_etudiants` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Adresse` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  `Numero_telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_etudiants`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `id_services` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Nature` VARCHAR(45) NULL,
  `Gratuite` VARCHAR(45) NULL,
  `Localisation` VARCHAR(45) NULL,
  `campus_id_campus` INT NOT NULL,
  PRIMARY KEY (`id_services`),
  INDEX `fk_services_campus1_idx` (`campus_id_campus` ASC) VISIBLE,
  CONSTRAINT `fk_services_campus1`
    FOREIGN KEY (`campus_id_campus`)
    REFERENCES `mydb`.`campus` (`id_campus`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employes_has_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employes_has_services` (
  `employes_id_employes` INT NOT NULL,
  `services_id_services` INT NOT NULL,
  PRIMARY KEY (`employes_id_employes`, `services_id_services`),
  INDEX `fk_employes_has_services_services1_idx` (`services_id_services` ASC) VISIBLE,
  INDEX `fk_employes_has_services_employes1_idx` (`employes_id_employes` ASC) VISIBLE,
  CONSTRAINT `fk_employes_has_services_employes1`
    FOREIGN KEY (`employes_id_employes`)
    REFERENCES `mydb`.`employes` (`id_employes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employes_has_services_services1`
    FOREIGN KEY (`services_id_services`)
    REFERENCES `mydb`.`services` (`id_services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etudiants_has_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etudiants_has_services` (
  `etudiants_id_etudiants` INT NOT NULL,
  `services_id_services` INT NOT NULL,
  PRIMARY KEY (`etudiants_id_etudiants`, `services_id_services`),
  INDEX `fk_etudiants_has_services_services1_idx` (`services_id_services` ASC) VISIBLE,
  INDEX `fk_etudiants_has_services_etudiants1_idx` (`etudiants_id_etudiants` ASC) VISIBLE,
  CONSTRAINT `fk_etudiants_has_services_etudiants1`
    FOREIGN KEY (`etudiants_id_etudiants`)
    REFERENCES `mydb`.`etudiants` (`id_etudiants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etudiants_has_services_services1`
    FOREIGN KEY (`services_id_services`)
    REFERENCES `mydb`.`services` (`id_services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employes_has_campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employes_has_campus` (
  `employes_id_employes` INT NOT NULL,
  `campus_id_campus` INT NOT NULL,
  PRIMARY KEY (`employes_id_employes`, `campus_id_campus`),
  INDEX `fk_employes_has_campus_campus1_idx` (`campus_id_campus` ASC) VISIBLE,
  INDEX `fk_employes_has_campus_employes1_idx` (`employes_id_employes` ASC) VISIBLE,
  CONSTRAINT `fk_employes_has_campus_employes1`
    FOREIGN KEY (`employes_id_employes`)
    REFERENCES `mydb`.`employes` (`id_employes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employes_has_campus_campus1`
    FOREIGN KEY (`campus_id_campus`)
    REFERENCES `mydb`.`campus` (`id_campus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etudiants_has_campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etudiants_has_campus` (
  `etudiants_id_etudiants` INT NOT NULL,
  `campus_id_campus` INT NOT NULL,
  PRIMARY KEY (`etudiants_id_etudiants`, `campus_id_campus`),
  INDEX `fk_etudiants_has_campus_campus1_idx` (`campus_id_campus` ASC) VISIBLE,
  INDEX `fk_etudiants_has_campus_etudiants1_idx` (`etudiants_id_etudiants` ASC) VISIBLE,
  CONSTRAINT `fk_etudiants_has_campus_etudiants1`
    FOREIGN KEY (`etudiants_id_etudiants`)
    REFERENCES `mydb`.`etudiants` (`id_etudiants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etudiants_has_campus_campus1`
    FOREIGN KEY (`campus_id_campus`)
    REFERENCES `mydb`.`campus` (`id_campus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filieres_has_etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filieres_has_etudiants` (
  `filieres_id_filieres` INT NOT NULL,
  `etudiants_id_etudiants` INT NOT NULL,
  PRIMARY KEY (`filieres_id_filieres`, `etudiants_id_etudiants`),
  INDEX `fk_filieres_has_etudiants_etudiants1_idx` (`etudiants_id_etudiants` ASC) VISIBLE,
  INDEX `fk_filieres_has_etudiants_filieres1_idx` (`filieres_id_filieres` ASC) VISIBLE,
  CONSTRAINT `fk_filieres_has_etudiants_filieres1`
    FOREIGN KEY (`filieres_id_filieres`)
    REFERENCES `mydb`.`filieres` (`id_filieres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filieres_has_etudiants_etudiants1`
    FOREIGN KEY (`etudiants_id_etudiants`)
    REFERENCES `mydb`.`etudiants` (`id_etudiants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classes_has_campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classes_has_campus` (
  `classes_id_classes` INT NOT NULL,
  `campus_id_campus` INT NOT NULL,
  PRIMARY KEY (`classes_id_classes`, `campus_id_campus`),
  INDEX `fk_classes_has_campus_campus1_idx` (`campus_id_campus` ASC) VISIBLE,
  INDEX `fk_classes_has_campus_classes1_idx` (`classes_id_classes` ASC) VISIBLE,
  CONSTRAINT `fk_classes_has_campus_classes1`
    FOREIGN KEY (`classes_id_classes`)
    REFERENCES `mydb`.`classes` (`id_classes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_campus_campus1`
    FOREIGN KEY (`campus_id_campus`)
    REFERENCES `mydb`.`campus` (`id_campus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cours_has_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cours_has_classes` (
  `cours_id_cours` INT NOT NULL,
  `classes_id_classes` INT NOT NULL,
  PRIMARY KEY (`cours_id_cours`, `classes_id_classes`),
  INDEX `fk_cours_has_classes_classes1_idx` (`classes_id_classes` ASC) VISIBLE,
  INDEX `fk_cours_has_classes_cours1_idx` (`cours_id_cours` ASC) VISIBLE,
  CONSTRAINT `fk_cours_has_classes_cours1`
    FOREIGN KEY (`cours_id_cours`)
    REFERENCES `mydb`.`cours` (`id_cours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cours_has_classes_classes1`
    FOREIGN KEY (`classes_id_classes`)
    REFERENCES `mydb`.`classes` (`id_classes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
