-- MySQL Script generated by MySQL Workbench
-- Sun Feb 14 13:52:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`regions_commerciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`regions_commerciales` (
  `id_region` INT NOT NULL,
  `nom_region` VARCHAR(45) NULL,
  `nom_responsable` VARCHAR(45) NULL,
  PRIMARY KEY (`id_region`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agences` (
  `id_agence` INT NOT NULL,
  `iid_region` INT NOT NULL,
  PRIMARY KEY (`id_agence`, `iid_region`),
  INDEX `fk_agences_regions_commerciales_idx` (`iid_region` ASC) VISIBLE,
  CONSTRAINT `fk_agences_regions_commerciales`
    FOREIGN KEY (`iid_region`)
    REFERENCES `mydb`.`regions_commerciales` (`id_region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrats` (
  `id_contrats` INT NOT NULL,
  `valeur_contrat` DECIMAL(5) NULL,
  `agences_id_agence` INT NOT NULL,
  `t` VARCHAR(45) NULL,
  PRIMARY KEY (`id_contrats`),
  INDEX `fk_contrats_agences1_idx` (`agences_id_agence` ASC) VISIBLE,
  CONSTRAINT `fk_contrats_agences1`
    FOREIGN KEY (`agences_id_agence`)
    REFERENCES `mydb`.`agences` (`id_agence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zonier_rn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zonier_rn` (
  `idzonier_rn` INT NOT NULL,
  `niv_risq` VARCHAR(45) NULL,
  PRIMARY KEY (`idzonier_rn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sites` (
  `id_site` INT NOT NULL,
  `valeur_site` DECIMAL(5) NULL,
  `contrats_id_contrats` INT NOT NULL,
  `zonier_rn_idzonier_rn` INT NOT NULL,
  PRIMARY KEY (`id_site`, `contrats_id_contrats`, `zonier_rn_idzonier_rn`),
  INDEX `fk_sites_contrats1_idx` (`contrats_id_contrats` ASC) VISIBLE,
  INDEX `fk_sites_zonier_rn1_idx` (`zonier_rn_idzonier_rn` ASC) VISIBLE,
  CONSTRAINT `fk_sites_contrats1`
    FOREIGN KEY (`contrats_id_contrats`)
    REFERENCES `mydb`.`contrats` (`id_contrats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sites_zonier_rn1`
    FOREIGN KEY (`zonier_rn_idzonier_rn`)
    REFERENCES `mydb`.`zonier_rn` (`idzonier_rn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
