-- MySQL Script generated by MySQL Workbench
-- Tue Feb 23 07:43:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`playlist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`playlist` (
  `idplaylist` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idplaylist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`date_added`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`date_added` ;

CREATE TABLE IF NOT EXISTS `mydb`.`date_added` (
  `iddate_added` INT NOT NULL,
  `date_added` DATETIME NULL,
  PRIMARY KEY (`iddate_added`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `idgenre` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`like` ;

CREATE TABLE IF NOT EXISTS `mydb`.`like` (
  `idlike` INT NOT NULL,
  `bool` TINYINT NULL,
  PRIMARY KEY (`idlike`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`song` ;

CREATE TABLE IF NOT EXISTS `mydb`.`song` (
  `idtitle` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `artist_idartist` INT NOT NULL,
  `date_added_iddate_added` INT NOT NULL,
  `like_idlike` INT NOT NULL,
  `genre_idgenre` INT NOT NULL,
  `playlist_idplaylist` INT NOT NULL,
  PRIMARY KEY (`idtitle`, `artist_idartist`, `date_added_iddate_added`, `like_idlike`, `genre_idgenre`, `playlist_idplaylist`),
  INDEX `fk_song_date_added1_idx` (`date_added_iddate_added` ASC) VISIBLE,
  INDEX `fk_song_like1_idx` (`like_idlike` ASC) VISIBLE,
  INDEX `fk_song_genre1_idx` (`genre_idgenre` ASC) VISIBLE,
  INDEX `fk_song_playlist1_idx` (`playlist_idplaylist` ASC) VISIBLE,
  CONSTRAINT `fk_song_date_added1`
    FOREIGN KEY (`date_added_iddate_added`)
    REFERENCES `mydb`.`date_added` (`iddate_added`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_song_like1`
    FOREIGN KEY (`like_idlike`)
    REFERENCES `mydb`.`like` (`idlike`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_song_genre1`
    FOREIGN KEY (`genre_idgenre`)
    REFERENCES `mydb`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_song_playlist1`
    FOREIGN KEY (`playlist_idplaylist`)
    REFERENCES `mydb`.`playlist` (`idplaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`artist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`artist` (
  `idartist` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `date_of_birth` DATE NULL,
  `song_idtitle` INT NOT NULL,
  `song_artist_idartist` INT NOT NULL,
  `song_date_added_iddate_added` INT NOT NULL,
  `song_like_idlike` INT NOT NULL,
  `song_genre_idgenre` INT NOT NULL,
  `song_playlist_idplaylist` INT NOT NULL,
  PRIMARY KEY (`idartist`, `song_idtitle`, `song_artist_idartist`, `song_date_added_iddate_added`, `song_like_idlike`, `song_genre_idgenre`, `song_playlist_idplaylist`),
  INDEX `fk_artist_song1_idx` (`song_idtitle` ASC, `song_artist_idartist` ASC, `song_date_added_iddate_added` ASC, `song_like_idlike` ASC, `song_genre_idgenre` ASC, `song_playlist_idplaylist` ASC) VISIBLE,
  CONSTRAINT `fk_artist_song1`
    FOREIGN KEY (`song_idtitle` , `song_artist_idartist` , `song_date_added_iddate_added` , `song_like_idlike` , `song_genre_idgenre` , `song_playlist_idplaylist`)
    REFERENCES `mydb`.`song` (`idtitle` , `artist_idartist` , `date_added_iddate_added` , `like_idlike` , `genre_idgenre` , `playlist_idplaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
