-- MySQL Script generated by MySQL Workbench
-- Tue Feb 23 08:20:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`playlist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`playlist` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`date_added`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`date_added` ;

CREATE TABLE IF NOT EXISTS `mydb`.`date_added` (
  `id` INT NOT NULL,
  `date_added` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`liked`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`liked` ;

CREATE TABLE IF NOT EXISTS `mydb`.`liked` (
  `id` INT NOT NULL,
  `bool` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`song` ;

CREATE TABLE IF NOT EXISTS `mydb`.`song` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `artist_id` INT NOT NULL,
  `date_added_id` INT NOT NULL,
  `liked_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  `playlist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `artist_id`, `date_added_id`, `liked_id`, `genre_id`, `playlist_id`),
  INDEX `fk_song_date_added1_idx` (`date_added_id` ASC) VISIBLE,
  INDEX `fk_song_like1_idx` (`liked_id` ASC) VISIBLE,
  INDEX `fk_song_genre1_idx` (`genre_id` ASC) VISIBLE,
  INDEX `fk_song_playlist1_idx` (`playlist_id` ASC) VISIBLE,
  CONSTRAINT `fk_song_date_added1`
    FOREIGN KEY (`date_added_id`)
    REFERENCES `mydb`.`date_added` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_song_like1`
    FOREIGN KEY (`liked_id`)
    REFERENCES `mydb`.`liked` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_song_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `mydb`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_song_playlist1`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `mydb`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`artist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`artist` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `date_of_birth` DATE NULL,
  `song_idtitle` INT NOT NULL,
  `song_artist_idartist` INT NOT NULL,
  `song_date_added_iddate_added` INT NOT NULL,
  `song_like_idlike` INT NOT NULL,
  `song_genre_idgenre` INT NOT NULL,
  `song_playlist_idplaylist` INT NOT NULL,
  PRIMARY KEY (`id`, `song_idtitle`, `song_artist_idartist`, `song_date_added_iddate_added`, `song_like_idlike`, `song_genre_idgenre`, `song_playlist_idplaylist`),
  INDEX `fk_artist_song1_idx` (`song_idtitle` ASC, `song_artist_idartist` ASC, `song_date_added_iddate_added` ASC, `song_like_idlike` ASC, `song_genre_idgenre` ASC, `song_playlist_idplaylist` ASC) VISIBLE,
  CONSTRAINT `fk_artist_song1`
    FOREIGN KEY (`song_idtitle` , `song_artist_idartist` , `song_date_added_iddate_added` , `song_like_idlike` , `song_genre_idgenre` , `song_playlist_idplaylist`)
    REFERENCES `mydb`.`song` (`id` , `artist_id` , `date_added_id` , `liked_id` , `genre_id` , `playlist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
