-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 08:26:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`domaine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`domaine` (
  `id_domaine` INT NOT NULL AUTO_INCREMENT,
  `domaine` VARCHAR(45) NULL,
  PRIMARY KEY (`id_domaine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprunt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprunt` (
  `id_emprunt` INT NOT NULL AUTO_INCREMENT,
  `disponiblite` VARCHAR(45) NULL,
  `date_emprunt` DATE NULL,
  `date_rendu` DATE NULL,
  PRIMARY KEY (`id_emprunt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livre` (
  `id_livre` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `editeur` VARCHAR(45) NULL,
  `année` VARCHAR(45) NULL,
  `domaine_id_domaine` INT NOT NULL,
  `emprunt_id_emprunt` INT NOT NULL,
  PRIMARY KEY (`id_livre`, `domaine_id_domaine`, `emprunt_id_emprunt`),
  INDEX `fk_livre_domaine1_idx` (`domaine_id_domaine` ASC) VISIBLE,
  INDEX `fk_livre_emprunt1_idx` (`emprunt_id_emprunt` ASC) VISIBLE,
  CONSTRAINT `fk_livre_domaine1`
    FOREIGN KEY (`domaine_id_domaine`)
    REFERENCES `mydb`.`domaine` (`id_domaine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_emprunt1`
    FOREIGN KEY (`emprunt_id_emprunt`)
    REFERENCES `mydb`.`emprunt` (`id_emprunt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auteur` (
  `id_auteur` INT NOT NULL,
  `nom_auteur` VARCHAR(45) NULL,
  `_auteur` VARCHAR(45) NULL,
  PRIMARY KEY (`id_auteur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`abonne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`abonne` (
  `id_abonne` INT NOT NULL AUTO_INCREMENT,
  `nom_abonne` VARCHAR(45) NULL,
  `prenom_abonne` VARCHAR(45) NULL,
  `telephone_abonne` VARCHAR(45) NULL,
  `mail_abonne` VARCHAR(45) NULL,
  `adresse_abonne` VARCHAR(45) NULL,
  `emprunt_id_emprunt` INT NOT NULL,
  PRIMARY KEY (`id_abonne`, `emprunt_id_emprunt`),
  INDEX `fk_abonne_emprunt1_idx` (`emprunt_id_emprunt` ASC) VISIBLE,
  CONSTRAINT `fk_abonne_emprunt1`
    FOREIGN KEY (`emprunt_id_emprunt`)
    REFERENCES `mydb`.`emprunt` (`id_emprunt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livre_has_auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livre_has_auteur` (
  `livre_id_livre` INT NOT NULL,
  `auteur_id_auteur` INT NOT NULL,
  PRIMARY KEY (`livre_id_livre`, `auteur_id_auteur`),
  INDEX `fk_livre_has_auteur_auteur1_idx` (`auteur_id_auteur` ASC) VISIBLE,
  INDEX `fk_livre_has_auteur_livre_idx` (`livre_id_livre` ASC) VISIBLE,
  CONSTRAINT `fk_livre_has_auteur_livre`
    FOREIGN KEY (`livre_id_livre`)
    REFERENCES `mydb`.`livre` (`id_livre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_has_auteur_auteur1`
    FOREIGN KEY (`auteur_id_auteur`)
    REFERENCES `mydb`.`auteur` (`id_auteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
