-- MySQL Script generated by MySQL Workbench
-- Tue May  4 11:02:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gestion_tests_COVID
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gestion_tests_COVID
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gestion_tests_COVID` DEFAULT CHARACTER SET utf8 ;
USE `Gestion_tests_COVID` ;

-- -----------------------------------------------------
-- Table `Gestion_tests_COVID`.`Tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_tests_COVID`.`Tests` (
  `idTests` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Cout_unit` DECIMAL(10,2) NOT NULL,
  `Pays_import` VARCHAR(45) NULL,
  PRIMARY KEY (`idTests`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_tests_COVID`.`Planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_tests_COVID`.`Planning` (
  `idPlanning` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Stock_total` INT NOT NULL,
  PRIMARY KEY (`idPlanning`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_tests_COVID`.`Tested_patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_tests_COVID`.`Tested_patient` (
  `idTested_patient` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Age` INT NOT NULL,
  `Ville` VARCHAR(45) NULL,
  `Symptome_principal` VARCHAR(45) NULL,
  `Planning_idPlanning` INT NOT NULL,
  `Tests_idTests` INT NOT NULL,
  PRIMARY KEY (`idTested_patient`, `Planning_idPlanning`, `Tests_idTests`),
  INDEX `fk_Tested_patient_Planning1_idx` (`Planning_idPlanning` ASC) ,
  INDEX `fk_Tested_patient_Tests1_idx` (`Tests_idTests` ASC) ,
  CONSTRAINT `fk_Tested_patient_Planning1`
    FOREIGN KEY (`Planning_idPlanning`)
    REFERENCES `Gestion_tests_COVID`.`Planning` (`idPlanning`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tested_patient_Tests1`
    FOREIGN KEY (`Tests_idTests`)
    REFERENCES `Gestion_tests_COVID`.`Tests` (`idTests`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_tests_COVID`.`Patient_for_rendezvous`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_tests_COVID`.`Patient_for_rendezvous` (
  `idTested_patient` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Age` INT NOT NULL,
  `Ville` VARCHAR(45) NULL,
  `Symptome_principal` VARCHAR(45) NULL,
  `Planning_idPlanning` INT NOT NULL,
  PRIMARY KEY (`idTested_patient`, `Planning_idPlanning`),
  INDEX `fk_Patient_for_rendezvous_Planning1_idx` (`Planning_idPlanning` ASC) ,
  CONSTRAINT `fk_Patient_for_rendezvous_Planning1`
    FOREIGN KEY (`Planning_idPlanning`)
    REFERENCES `Gestion_tests_COVID`.`Planning` (`idPlanning`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_tests_COVID`.`Tests_has_Planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_tests_COVID`.`Tests_has_Planning` (
  `Tests_idTests` INT NOT NULL,
  `Planning_idPlanning` INT NOT NULL,
  PRIMARY KEY (`Tests_idTests`, `Planning_idPlanning`),
  INDEX `fk_Tests_has_Planning_Planning1_idx` (`Planning_idPlanning` ASC) ,
  INDEX `fk_Tests_has_Planning_Tests_idx` (`Tests_idTests` ASC) ,
  CONSTRAINT `fk_Tests_has_Planning_Tests`
    FOREIGN KEY (`Tests_idTests`)
    REFERENCES `Gestion_tests_COVID`.`Tests` (`idTests`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tests_has_Planning_Planning1`
    FOREIGN KEY (`Planning_idPlanning`)
    REFERENCES `Gestion_tests_COVID`.`Planning` (`idPlanning`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Tests (Type, Cout_unit, Pays_import)
VALUES
('Antigénique', 3.5, 'Pologne'),
('RT-PCR', 12.7, 'Italie'),
('Salivaire', 7.4, 'France'),
('Sérologique', 13.1, 'Espagne');

INSERT INTO Planning (Date, Stock_total)
VALUES
('2021-05-07', 203151),
('2021-05-06', 199942),
('2021-05-05', 189654),
('2021-05-04', 148963),
('2021-05-03', 153677),
('2021-05-02', 168453),
('2021-05-01', 159634);

INSERT INTO Tests_has_Planning (Tests_idTests, Planning_idPlanning)
VALUES
(1, 1), (2, 1), (3, 1), (4, 1),
(1, 4), (2, 4), (3, 4),
(4, 2), (1, 2),
(1, 3), (2, 3), (4, 3),
(1, 5), (3, 5),
(1, 7);

INSERT INTO Patient_for_rendezvous (Nom, Prenom, Age, Ville, Symptome_principal, Planning_idPlanning)
VALUES
('Dupond', 'Louis', 25, 'Paris', 'Toux', 4),
('Durand', 'Jeanne', 68, 'Paris', 'Difficultés respiratoires', 1),
('Sianey', 'Therese', 63, 'Paris', 'Migraines', 1),
('Tribou', 'Paul', 42, 'Lyon', 'Perte de goût', 2),
('Blariot', 'Abdel', 37, 'Lyon', 'Toux', 3),
('Souchang', 'Leslie', 19, 'Lyon', 'Toux', 4),
('Milos', 'Zeus', 57, 'Marseille', 'Difficultés respiratoires', 2),
('Pulain', 'Cong', 17, 'Marseille', 'Migraines', 5),
('Labouil', 'Habess', 64, 'Marseille', 'Perte de goût', 6),
('Valjean', 'Jean', 54, 'Avignon', 'Perte de goût', 4),
('Carvana', 'Maxime', 33, 'Avignon', 'Toux', 7),
('Didlo', 'Samira', 85, 'Avignon', 'Difficultés respiratoires', 4);

INSERT INTO Tested_patient (Nom, Prenom, Age, Ville, Symptome_principal, Planning_idPlanning, Tests_idTests)
VALUES
('Soleil', 'Alexandre', 25, 'Paris', 'Toux', 4, 1),
('Monroe', 'Marine', 68, 'Paris', 'Difficultés respiratoires', 1, 2),
('Bonnay', 'Therese', 63, 'Paris', 'Migraines', 1, 2),
('Perrin', 'Paul', 42, 'Lyon', 'Perte de goût', 2, 1),
('Hassad', 'Omar', 37, 'Lyon', 'Toux', 3, 3),
('Soutiphong', 'Lizie', 19, 'Lyon', 'Toux', 4, 3),
('Bertrand', 'Francis', 57, 'Marseille', 'Difficultés respiratoires', 2, 2),
('Signorel', 'Micheline', 17, 'Marseille', 'Migraines', 5, 1),
('Zetong', 'Maya', 64, 'Marseille', 'Perte de goût', 6, 1),
('Ramirez', 'Pedro', 54, 'Avignon', 'Perte de goût', 4, 4),
('Vignac', 'Louis', 33, 'Avignon', 'Toux', 7, 4),
('Hugo', 'Victoria', 85, 'Avignon', 'Difficultés respiratoires', 4, 2);