-- MySQL Script generated by MySQL Workbench
-- Tue Feb  2 11:04:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema theatre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema theatre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `theatre` DEFAULT CHARACTER SET utf8 ;
USE `theatre` ;

-- -----------------------------------------------------
-- Table `theatre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theatre` ;

CREATE TABLE IF NOT EXISTS `theatre` (
  `id_theatre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `proprietaire` VARCHAR(45) NULL,
  PRIMARY KEY (`id_theatre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proprietaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proprietaire` ;

CREATE TABLE IF NOT EXISTS `proprietaire` (
  `id_proprietaire` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proprietaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theatre_has_proprietaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `theatre_has_proprietaire` ;

CREATE TABLE IF NOT EXISTS `theatre_has_proprietaire` (
  `theatre_id_theatre` INT NOT NULL,
  `proprietaire_id_proprietaire` INT NOT NULL,
  PRIMARY KEY (`theatre_id_theatre`, `proprietaire_id_proprietaire`),
  INDEX `fk_theatre_has_proprietaire_proprietaire1_idx` (`proprietaire_id_proprietaire` ASC) VISIBLE,
  INDEX `fk_theatre_has_proprietaire_theatre_idx` (`theatre_id_theatre` ASC) VISIBLE,
  CONSTRAINT `fk_theatre_has_proprietaire_theatre`
    FOREIGN KEY (`theatre_id_theatre`)
    REFERENCES `theatre` (`id_theatre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_theatre_has_proprietaire_proprietaire1`
    FOREIGN KEY (`proprietaire_id_proprietaire`)
    REFERENCES `proprietaire` (`id_proprietaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siege`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siege` ;

CREATE TABLE IF NOT EXISTS `siege` (
  `id_siege` INT NOT NULL AUTO_INCREMENT,
  `num` VARCHAR(45) NULL,
  `theatre_id_theatre` INT NOT NULL,
  PRIMARY KEY (`id_siege`, `theatre_id_theatre`),
  INDEX `fk_siege_theatre1_idx` (`theatre_id_theatre` ASC) VISIBLE,
  CONSTRAINT `fk_siege_theatre1`
    FOREIGN KEY (`theatre_id_theatre`)
    REFERENCES `theatre` (`id_theatre`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tarif` ;

CREATE TABLE IF NOT EXISTS `tarif` (
  `id_tarif` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prix` VARCHAR(45) NULL,
  `validite` DATETIME NULL,
  `siege_id_siege` INT NOT NULL,
  PRIMARY KEY (`id_tarif`),
  INDEX `fk_tarif_siege1_idx` (`siege_id_siege` ASC) VISIBLE,
  CONSTRAINT `fk_tarif_siege1`
    FOREIGN KEY (`siege_id_siege`)
    REFERENCES `siege` (`id_siege`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
