-- MySQL Script generated by MySQL Workbench
-- Sun Feb 14 20:13:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `N° client` INT UNSIGNED NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(200) NOT NULL,
  `Code postal` VARCHAR(5) NOT NULL,
  `Ville` VARCHAR(100) NOT NULL,
  `Clientscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`N° client`),
  UNIQUE INDEX `N° client_UNIQUE` (`N° client` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commandes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commandes` (
  `N°Commande` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Adresse livraison` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`N°Commande`),
  UNIQUE INDEX `N°Commande_UNIQUE` (`N°Commande` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client-Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client-Commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client-Commande` (
  `FK_N°Client` INT NOT NULL,
  `FK_N°Commande` INT NOT NULL,
  PRIMARY KEY (`FK_N°Client`, `FK_N°Commande`),
  CONSTRAINT `FK_N°Client`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Clients` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_N°commande`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Commandes` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produit` (
  `N°Produit` INT NOT NULL,
  `Libellé` VARCHAR(200) NOT NULL,
  `Prix` DECIMAL NOT NULL,
  PRIMARY KEY (`N°Produit`),
  UNIQUE INDEX `N°Produit_UNIQUE` (`N°Produit` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commande_Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commande_Produit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commande_Produit` (
  `FK_N°Produit` INT NOT NULL,
  `FK_N°Commande` INT NOT NULL,
  PRIMARY KEY (`FK_N°Produit`, `FK_N°Commande`),
  CONSTRAINT `FK_N°Produit`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Produit` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_N°Commande`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Commandes` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
