-- MySQL Script generated by MySQL Workbench
-- Sat Feb  6 17:41:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livre` (
  `id_livre` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `nb_pages` INT NULL,
  PRIMARY KEY (`id_livre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `livre_id_livre` INT NOT NULL,
  PRIMARY KEY (`id_genre`, `livre_id_livre`),
  INDEX `fk_genre_livre1_idx` (`livre_id_livre` ASC) VISIBLE,
  CONSTRAINT `fk_genre_livre1`
    FOREIGN KEY (`livre_id_livre`)
    REFERENCES `mydb`.`livre` (`id_livre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auteur` (
  `id_auteur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `date_de_naissance` DATETIME NULL,
  PRIMARY KEY (`id_auteur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livre_has_auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livre_has_auteur` (
  `livre_id_livre` INT NOT NULL,
  `auteur_id_auteur` INT NOT NULL,
  PRIMARY KEY (`livre_id_livre`, `auteur_id_auteur`),
  INDEX `fk_livre_has_auteur_auteur1_idx` (`auteur_id_auteur` ASC) VISIBLE,
  INDEX `fk_livre_has_auteur_livre_idx` (`livre_id_livre` ASC) VISIBLE,
  CONSTRAINT `fk_livre_has_auteur_livre`
    FOREIGN KEY (`livre_id_livre`)
    REFERENCES `mydb`.`livre` (`id_livre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_has_auteur_auteur1`
    FOREIGN KEY (`auteur_id_auteur`)
    REFERENCES `mydb`.`auteur` (`id_auteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
