-- MySQL Script generated by MySQL Workbench
-- Tue May  4 10:36:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table `mydb`.`régions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`regions` (
  `code_insee_r` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`code_insee_r`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`départements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`departements` (
  `code_insee_d` INT NOT NULL,
  `code_insee_r` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`code_insee_d`),
    FOREIGN KEY (`code_insee_r`)
    REFERENCES `covid`.`regions` (`code_insee_r`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`centres de dépistage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`centres de depistage` (
  `id_centre` INT NOT NULL,
  `code_insee_d` INT NULL,
  `name` VARCHAR(45) NULL,
  `nbr_test` INT NULL,
  PRIMARY KEY (`id_centre`),
    FOREIGN KEY (`code_insee_d`)
    REFERENCES `covid`.`departements` (`code_insee_d`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`patients` (
  `id_patient` INT NOT NULL,
  `name_patient` VARCHAR(45) NULL,
  `id_centre` INT NULL,
  `date_rdv` DATE NULL,
  `date_depistage` DATE NULL,
  PRIMARY KEY (`id_patient`),
    FOREIGN KEY (`id_centre`)
    REFERENCES `covid`.`centres de depistage` (`id_centre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
