-- MySQL Script generated by MySQL Workbench
-- Tue Feb  2 10:40:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sportif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sportif` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sportif` (
  `idSportif` INT NOT NULL,
  `Nom_Sportif` VARCHAR(45) NULL,
  `Prenom_Sportif` VARCHAR(45) NULL,
  PRIMARY KEY (`idSportif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entraineur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entraineur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entraineur` (
  `idEntraineur` INT NOT NULL,
  `Nom_Entraineur` VARCHAR(45) NULL,
  `Prenom_Entraineur` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntraineur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gymnase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gymnase` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gymnase` (
  `idGymnase` INT NOT NULL,
  `Nom_Gymnase` VARCHAR(45) NULL,
  `Adresse` VARCHAR(45) NULL,
  PRIMARY KEY (`idGymnase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sports` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sports` (
  `idSports` INT NOT NULL,
  `Nom_Sport` VARCHAR(45) NULL,
  `Catégorie` VARCHAR(45) NULL,
  PRIMARY KEY (`idSports`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Seance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Seance` (
  `idSeance` INT NOT NULL,
  `Annee` INT NULL,
  `Mois` INT NULL,
  `Jour` INT NULL,
  `Heure` INT NULL,
  `Minute` INT NULL,
  `Gymnase_idGymnase` INT NOT NULL,
  `Sports_idSports` INT NOT NULL,
  PRIMARY KEY (`idSeance`, `Gymnase_idGymnase`, `Sports_idSports`),
  INDEX `fk_Seance_Gymnase1_idx` (`Gymnase_idGymnase` ASC) VISIBLE,
  INDEX `fk_Seance_Sports1_idx` (`Sports_idSports` ASC) VISIBLE,
  CONSTRAINT `fk_Seance_Gymnase1`
    FOREIGN KEY (`Gymnase_idGymnase`)
    REFERENCES `mydb`.`Gymnase` (`idGymnase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seance_Sports1`
    FOREIGN KEY (`Sports_idSports`)
    REFERENCES `mydb`.`Sports` (`idSports`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sportif_has_Seance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sportif_has_Seance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sportif_has_Seance` (
  `Sportif_idSportif` INT NOT NULL,
  `Seance_idSeance` INT NOT NULL,
  PRIMARY KEY (`Sportif_idSportif`, `Seance_idSeance`),
  INDEX `fk_Sportif_has_Seance_Seance1_idx` (`Seance_idSeance` ASC) VISIBLE,
  INDEX `fk_Sportif_has_Seance_Sportif1_idx` (`Sportif_idSportif` ASC) VISIBLE,
  CONSTRAINT `fk_Sportif_has_Seance_Sportif1`
    FOREIGN KEY (`Sportif_idSportif`)
    REFERENCES `mydb`.`Sportif` (`idSportif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sportif_has_Seance_Seance1`
    FOREIGN KEY (`Seance_idSeance`)
    REFERENCES `mydb`.`Seance` (`idSeance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seance_has_Entraineur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Seance_has_Entraineur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Seance_has_Entraineur` (
  `Seance_idSeance` INT NOT NULL,
  `Entraineur_idEntraineur` INT NOT NULL,
  `Entraineur_Sportif_idSportif` INT NOT NULL,
  PRIMARY KEY (`Seance_idSeance`, `Entraineur_idEntraineur`, `Entraineur_Sportif_idSportif`),
  INDEX `fk_Seance_has_Entraineur_Entraineur1_idx` (`Entraineur_idEntraineur` ASC, `Entraineur_Sportif_idSportif` ASC) VISIBLE,
  INDEX `fk_Seance_has_Entraineur_Seance1_idx` (`Seance_idSeance` ASC) VISIBLE,
  CONSTRAINT `fk_Seance_has_Entraineur_Seance1`
    FOREIGN KEY (`Seance_idSeance`)
    REFERENCES `mydb`.`Seance` (`idSeance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seance_has_Entraineur_Entraineur1`
    FOREIGN KEY (`Entraineur_idEntraineur`)
    REFERENCES `mydb`.`Entraineur` (`idEntraineur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
