-- MySQL Script generated by MySQL Workbench
-- Tue May  4 12:47:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patients` (
  `idpatients` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `age` INT NULL,
  `hebergement` VARCHAR(45) NULL,
  `raison_test` VARCHAR(45) NULL,
  `num_patients_rdv` INT NULL,
  `centre de dépistage_idcentre de dépistage` INT NOT NULL,
  `centre de dépistage_tests_id_test` INT NOT NULL,
  `centre de dépistage_patients_idpatients` INT NOT NULL,
  PRIMARY KEY (`idpatients`, `centre de dépistage_idcentre de dépistage`, `centre de dépistage_tests_id_test`, `centre de dépistage_patients_idpatients`),
  INDEX `fk_patients_centre de dépistage1_idx` (`centre de dépistage_idcentre de dépistage` ASC, `centre de dépistage_tests_id_test` ASC, `centre de dépistage_patients_idpatients` ASC) VISIBLE,
  CONSTRAINT `fk_patients_centre de dépistage1`
    FOREIGN KEY (`centre de dépistage_idcentre de dépistage` , `centre de dépistage_tests_id_test` , `centre de dépistage_patients_idpatients`)
    REFERENCES `mydb`.`centre de dépistage` (`idcentre de dépistage` , `tests_id_test` , `patients_idpatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`centre de dépistage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`centre de dépistage` (
  `idcentre de dépistage` INT NOT NULL,
  `adresse` VARCHAR(45) NULL,
  `nb_patients_testes` INT NULL,
  `num_patients_rdv` INT NULL,
  `tests_id_test` INT NOT NULL,
  `patients_idpatients` INT NOT NULL,
  PRIMARY KEY (`idcentre de dépistage`, `tests_id_test`, `patients_idpatients`),
  INDEX `fk_centre de dépistage_tests_idx` (`tests_id_test` ASC) VISIBLE,
  INDEX `fk_centre de dépistage_patients1_idx` (`patients_idpatients` ASC) VISIBLE,
  CONSTRAINT `fk_centre de dépistage_tests`
    FOREIGN KEY (`tests_id_test`)
    REFERENCES `mydb`.`tests` (`id_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_centre de dépistage_patients1`
    FOREIGN KEY (`patients_idpatients`)
    REFERENCES `mydb`.`patients` (`idpatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tests` (
  `id_test` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `date` DATE NULL,
  `qtite_tests_dispo` INT NULL,
  `centre de dépistage_idcentre de dépistage` INT NOT NULL,
  `centre de dépistage_tests_id_test` INT NOT NULL,
  PRIMARY KEY (`id_test`, `centre de dépistage_idcentre de dépistage`, `centre de dépistage_tests_id_test`),
  INDEX `fk_tests_centre de dépistage1_idx` (`centre de dépistage_idcentre de dépistage` ASC, `centre de dépistage_tests_id_test` ASC) VISIBLE,
  CONSTRAINT `fk_tests_centre de dépistage1`
    FOREIGN KEY (`centre de dépistage_idcentre de dépistage` , `centre de dépistage_tests_id_test`)
    REFERENCES `mydb`.`centre de dépistage` (`idcentre de dépistage` , `tests_id_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
