-- MySQL Script generated by MySQL Workbench
-- Tue Feb  2 10:32:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`FILM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FILM` (
  `FI_Code` INT NOT NULL AUTO_INCREMENT,
  `FI_Nom` VARCHAR(45) NULL,
  `FI_Duree` INT NULL,
  PRIMARY KEY (`FI_Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ACTEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ACTEUR` (
  `ACT_Code` INT NOT NULL AUTO_INCREMENT,
  `ACT_DateNaiss` DATE NULL,
  `ACT_Nationalite` VARCHAR(25) NULL,
  `ACT_Nom` VARCHAR(45) NULL,
  `ACT_Prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`ACT_Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FILM_has_ACTEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FILM_has_ACTEUR` (
  `FILM_FI_Code` INT NOT NULL,
  `ACTEUR_ACT_Code` INT NOT NULL,
  PRIMARY KEY (`FILM_FI_Code`, `ACTEUR_ACT_Code`),
  INDEX `fk_FILM_has_ACTEUR_ACTEUR1_idx` (`ACTEUR_ACT_Code` ASC) VISIBLE,
  INDEX `fk_FILM_has_ACTEUR_FILM_idx` (`FILM_FI_Code` ASC) VISIBLE,
  CONSTRAINT `fk_FILM_has_ACTEUR_FILM`
    FOREIGN KEY (`FILM_FI_Code`)
    REFERENCES `mydb`.`FILM` (`FI_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FILM_has_ACTEUR_ACTEUR1`
    FOREIGN KEY (`ACTEUR_ACT_Code`)
    REFERENCES `mydb`.`ACTEUR` (`ACT_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CINEMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CINEMA` (
  `CIN_Code` INT NOT NULL AUTO_INCREMENT,
  `CIN_Nom` VARCHAR(45) NULL,
  `CIN_Adr` VARCHAR(45) NULL,
  `CIN_Ville` VARCHAR(45) NULL,
  `CIN_CP` VARCHAR(5) NULL,
  PRIMARY KEY (`CIN_Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FILM_has_CINEMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FILM_has_CINEMA` (
  `FILM_FI_Code` INT NOT NULL,
  `CINEMA_CIN_Code` INT NOT NULL,
  PRIMARY KEY (`FILM_FI_Code`, `CINEMA_CIN_Code`),
  INDEX `fk_FILM_has_CINEMA_CINEMA1_idx` (`CINEMA_CIN_Code` ASC) VISIBLE,
  INDEX `fk_FILM_has_CINEMA_FILM1_idx` (`FILM_FI_Code` ASC) VISIBLE,
  CONSTRAINT `fk_FILM_has_CINEMA_FILM1`
    FOREIGN KEY (`FILM_FI_Code`)
    REFERENCES `mydb`.`FILM` (`FI_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FILM_has_CINEMA_CINEMA1`
    FOREIGN KEY (`CINEMA_CIN_Code`)
    REFERENCES `mydb`.`CINEMA` (`CIN_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SALLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SALLE` (
  `SA_Code` INT NOT NULL AUTO_INCREMENT,
  `SA_NbPlace` INT NULL,
  `CINEMA_CIN_Code` INT NOT NULL,
  PRIMARY KEY (`SA_Code`, `CINEMA_CIN_Code`),
  INDEX `fk_SALLE_CINEMA1_idx` (`CINEMA_CIN_Code` ASC) INVISIBLE,
  CONSTRAINT `fk_SALLE_CINEMA1`
    FOREIGN KEY (`CINEMA_CIN_Code`)
    REFERENCES `mydb`.`CINEMA` (`CIN_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SALLE_has_FILM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SALLE_has_FILM` (
  `SALLE_SA_Code` INT NOT NULL,
  `SALLE_CINEMA_CIN_Code` INT NOT NULL,
  `FILM_FI_Code` INT NOT NULL,
  PRIMARY KEY (`SALLE_SA_Code`, `SALLE_CINEMA_CIN_Code`, `FILM_FI_Code`),
  INDEX `fk_SALLE_has_FILM_FILM1_idx` (`FILM_FI_Code` ASC) VISIBLE,
  INDEX `fk_SALLE_has_FILM_SALLE1_idx` (`SALLE_SA_Code` ASC, `SALLE_CINEMA_CIN_Code` ASC) VISIBLE,
  CONSTRAINT `fk_SALLE_has_FILM_SALLE1`
    FOREIGN KEY (`SALLE_SA_Code` , `SALLE_CINEMA_CIN_Code`)
    REFERENCES `mydb`.`SALLE` (`SA_Code` , `CINEMA_CIN_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SALLE_has_FILM_FILM1`
    FOREIGN KEY (`FILM_FI_Code`)
    REFERENCES `mydb`.`FILM` (`FI_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SEANCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SEANCE` (
  `SE_Code` INT NOT NULL,
  `SE_Prix` FLOAT NULL,
  `SE_Date` DATE NULL,
  `SE_Horraire` TIME NULL,
  `SALLE_has_FILM_SALLE_SA_Code` INT NOT NULL,
  `SALLE_has_FILM_SALLE_CINEMA_CIN_Code` INT NOT NULL,
  `SALLE_has_FILM_FILM_FI_Code` INT NOT NULL,
  PRIMARY KEY (`SE_Code`, `SALLE_has_FILM_SALLE_SA_Code`, `SALLE_has_FILM_SALLE_CINEMA_CIN_Code`, `SALLE_has_FILM_FILM_FI_Code`),
  INDEX `fk_SEANCE_SALLE_has_FILM1_idx` (`SALLE_has_FILM_SALLE_SA_Code` ASC, `SALLE_has_FILM_SALLE_CINEMA_CIN_Code` ASC, `SALLE_has_FILM_FILM_FI_Code` ASC) VISIBLE,
  CONSTRAINT `fk_SEANCE_SALLE_has_FILM1`
    FOREIGN KEY (`SALLE_has_FILM_SALLE_SA_Code` , `SALLE_has_FILM_SALLE_CINEMA_CIN_Code` , `SALLE_has_FILM_FILM_FI_Code`)
    REFERENCES `mydb`.`SALLE_has_FILM` (`SALLE_SA_Code` , `SALLE_CINEMA_CIN_Code` , `FILM_FI_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENT` (
  `CLI_Code` INT NOT NULL,
  `CLI_Prenom` VARCHAR(45) NULL,
  `CLI_Nom` VARCHAR(45) NULL,
  `CLI_Adr` VARCHAR(45) NULL,
  `CLI_Ville` VARCHAR(45) NULL,
  `CLI_CP` VARCHAR(5) NULL,
  PRIMARY KEY (`CLI_Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SEANCE_has_CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SEANCE_has_CLIENT` (
  `SEANCE_SE_Code` INT NOT NULL,
  `SEANCE_SALLE_has_FILM_SALLE_SA_Code` INT NOT NULL,
  `SEANCE_SALLE_has_FILM_SALLE_CINEMA_CIN_Code` INT NOT NULL,
  `SEANCE_SALLE_has_FILM_FILM_FI_Code` INT NOT NULL,
  `CLIENT_CLI_Code` INT NOT NULL,
  PRIMARY KEY (`SEANCE_SE_Code`, `SEANCE_SALLE_has_FILM_SALLE_SA_Code`, `SEANCE_SALLE_has_FILM_SALLE_CINEMA_CIN_Code`, `SEANCE_SALLE_has_FILM_FILM_FI_Code`, `CLIENT_CLI_Code`),
  INDEX `fk_SEANCE_has_CLIENT_CLIENT1_idx` (`CLIENT_CLI_Code` ASC) VISIBLE,
  INDEX `fk_SEANCE_has_CLIENT_SEANCE1_idx` (`SEANCE_SE_Code` ASC, `SEANCE_SALLE_has_FILM_SALLE_SA_Code` ASC, `SEANCE_SALLE_has_FILM_SALLE_CINEMA_CIN_Code` ASC, `SEANCE_SALLE_has_FILM_FILM_FI_Code` ASC) VISIBLE,
  CONSTRAINT `fk_SEANCE_has_CLIENT_SEANCE1`
    FOREIGN KEY (`SEANCE_SE_Code` , `SEANCE_SALLE_has_FILM_SALLE_SA_Code` , `SEANCE_SALLE_has_FILM_SALLE_CINEMA_CIN_Code` , `SEANCE_SALLE_has_FILM_FILM_FI_Code`)
    REFERENCES `mydb`.`SEANCE` (`SE_Code` , `SALLE_has_FILM_SALLE_SA_Code` , `SALLE_has_FILM_SALLE_CINEMA_CIN_Code` , `SALLE_has_FILM_FILM_FI_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SEANCE_has_CLIENT_CLIENT1`
    FOREIGN KEY (`CLIENT_CLI_Code`)
    REFERENCES `mydb`.`CLIENT` (`CLI_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
