-- MySQL Script generated by MySQL Workbench
-- Tue May  4 16:55:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_db
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema omk_medas1_20-21
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patient` ;

CREATE TABLE IF NOT EXISTS `patient` (
  `id_patient` INT(11) NOT NULL AUTO_INCREMENT,
  `pa_nom` VARCHAR(45) NULL DEFAULT NULL,
  `pa_date_naissance` DATE NULL DEFAULT NULL,
  `pa_num_secu` VARCHAR(45) NULL DEFAULT NULL,
  `pa_tel` VARCHAR(45) NULL DEFAULT NULL,
  `pa_mail` VARCHAR(45) NULL DEFAULT NULL,
  `pa_adresse` VARCHAR(45) NULL DEFAULT NULL,
  `pa_ville` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_patient`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rendez_vous`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rendez_vous` ;

CREATE TABLE IF NOT EXISTS `rendez_vous` (
  `id_rendez_vous` INT(11) NOT NULL AUTO_INCREMENT,
  `rv_date` DATE NULL DEFAULT NULL,
  `rv_heure` TIME NULL DEFAULT NULL,
  `patient_id_patient` INT(11) NOT NULL,
  PRIMARY KEY (`id_rendez_vous`),
  INDEX `fk_rendez_vous_patient_idx` (`patient_id_patient` ASC),
  CONSTRAINT `fk_rendez_vous_patient`
    FOREIGN KEY (`patient_id_patient`)
    REFERENCES `patient` (`id_patient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test` ;

CREATE TABLE IF NOT EXISTS `test` (
  `id_test` INT(11) NOT NULL AUTO_INCREMENT,
  `te_date` DATE NULL DEFAULT NULL,
  `te_heure` TIME NULL DEFAULT NULL,
  `te_resultat` VARCHAR(45) NULL DEFAULT NULL,
  `rendez_vous_id_rendez_vous` INT(11) NOT NULL,
  PRIMARY KEY (`id_test`),
  INDEX `fk_test_rendez_vous1_idx` (`rendez_vous_id_rendez_vous` ASC),
  CONSTRAINT `fk_test_rendez_vous1`
    FOREIGN KEY (`rendez_vous_id_rendez_vous`)
    REFERENCES `rendez_vous` (`id_rendez_vous`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact` ;

CREATE TABLE IF NOT EXISTS `contact` (
  `id_contact` INT(11) NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(45) NULL DEFAULT NULL,
  `ville` VARCHAR(45) NULL DEFAULT NULL,
  `code_postal` INT(11) NULL DEFAULT NULL,
  `tel` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contact`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `association`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `association` ;

CREATE TABLE IF NOT EXISTS `association` (
  `id_association` INT(11) NOT NULL AUTO_INCREMENT,
  `ass_nom` VARCHAR(45) NULL DEFAULT NULL,
  `ass_statut` VARCHAR(45) NULL DEFAULT NULL,
  `ass_heure_recrut` FLOAT NULL DEFAULT NULL,
  `contact_id_contact` INT(11) NOT NULL,
  PRIMARY KEY (`id_association`),
  INDEX `fk_association_contact1_idx` (`contact_id_contact` ASC),
  CONSTRAINT `fk_association_contact1`
    FOREIGN KEY (`contact_id_contact`)
    REFERENCES `contact` (`id_contact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coor_ban`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coor_ban` ;

CREATE TABLE IF NOT EXISTS `coor_ban` (
  `id_coor_ban` INT(11) NOT NULL AUTO_INCREMENT,
  `coor_banc_ib` VARCHAR(45) NULL DEFAULT NULL,
  `coor_banc_bi` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_coor_ban`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `donateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `donateur` ;

CREATE TABLE IF NOT EXISTS `donateur` (
  `id_donateur` INT(11) NOT NULL AUTO_INCREMENT,
  `don_type` VARCHAR(45) NULL DEFAULT NULL,
  `don_nom` VARCHAR(45) NULL DEFAULT NULL,
  `don_prenom` VARCHAR(45) NULL DEFAULT NULL,
  `don_genre` VARCHAR(45) NULL DEFAULT NULL,
  `don_naissance` DATE NULL DEFAULT NULL,
  `coor_ban_id_coor_ban` INT(11) NOT NULL,
  `contact_id_contact` INT(11) NOT NULL,
  PRIMARY KEY (`id_donateur`),
  INDEX `fk_donateur_coor_ban1_idx` (`coor_ban_id_coor_ban` ASC),
  INDEX `fk_donateur_contact1_idx` (`contact_id_contact` ASC),
  CONSTRAINT `fk_donateur_contact1`
    FOREIGN KEY (`contact_id_contact`)
    REFERENCES `contact` (`id_contact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_donateur_coor_ban1`
    FOREIGN KEY (`coor_ban_id_coor_ban`)
    REFERENCES `coor_ban` (`id_coor_ban`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coor_ban_rec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coor_ban_rec` ;

CREATE TABLE IF NOT EXISTS `coor_ban_rec` (
  `id_coor_ban_rec` INT(11) NOT NULL,
  `coor_banc_ib_rec` VARCHAR(45) NULL DEFAULT NULL,
  `coor_banc_bi_rec` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_coor_ban_rec`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recruteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruteur` ;

CREATE TABLE IF NOT EXISTS `recruteur` (
  `id_recruteur` INT(11) NOT NULL AUTO_INCREMENT,
  `rec_nom` VARCHAR(45) NULL DEFAULT NULL,
  `rec_prenom` VARCHAR(45) NULL DEFAULT NULL,
  `rec_naissance` DATE NULL DEFAULT NULL,
  `rec_statut` VARCHAR(45) NULL DEFAULT NULL,
  `rec_heure_t` FLOAT NULL DEFAULT NULL,
  `rec_heure_r` FLOAT NULL DEFAULT NULL,
  `rec_numero_secu` VARCHAR(45) NULL DEFAULT NULL,
  `contact_id_contact` INT(11) NOT NULL,
  `coor_ban_rec_id_coor_ban_rec` INT(11) NOT NULL,
  PRIMARY KEY (`id_recruteur`),
  INDEX `fk_recruteur_contact1_idx` (`contact_id_contact` ASC),
  INDEX `fk_recruteur_coor_ban_rec1_idx` (`coor_ban_rec_id_coor_ban_rec` ASC),
  CONSTRAINT `fk_recruteur_contact1`
    FOREIGN KEY (`contact_id_contact`)
    REFERENCES `contact` (`id_contact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recruteur_coor_ban_rec1`
    FOREIGN KEY (`coor_ban_rec_id_coor_ban_rec`)
    REFERENCES `coor_ban_rec` (`id_coor_ban_rec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `adhesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adhesion` ;

CREATE TABLE IF NOT EXISTS `adhesion` (
  `id_adhesion` INT(11) NOT NULL AUTO_INCREMENT,
  `ad_montant` INT(11) NULL DEFAULT NULL,
  `ad_statut` VARCHAR(45) NULL DEFAULT NULL,
  `ad_date_debut` DATE NULL DEFAULT NULL,
  `ad_date_fin` DATE NULL DEFAULT NULL,
  `association_id_association` INT(11) NOT NULL,
  `donateur_id_donateur` INT(11) NOT NULL,
  `recruteur_id_recruteur` INT(11) NOT NULL,
  PRIMARY KEY (`id_adhesion`),
  INDEX `fk_adhesion_association1_idx` (`association_id_association` ASC),
  INDEX `fk_adhesion_donateur1_idx` (`donateur_id_donateur` ASC),
  INDEX `fk_adhesion_recruteur1_idx` (`recruteur_id_recruteur` ASC),
  CONSTRAINT `fk_adhesion_association1`
    FOREIGN KEY (`association_id_association`)
    REFERENCES `association` (`id_association`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adhesion_donateur1`
    FOREIGN KEY (`donateur_id_donateur`)
    REFERENCES `donateur` (`id_donateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adhesion_recruteur1`
    FOREIGN KEY (`recruteur_id_recruteur`)
    REFERENCES `recruteur` (`id_recruteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(190) NOT NULL,
  `name` VARCHAR(190) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `password_hash` VARCHAR(60) NULL DEFAULT NULL,
  `role` VARCHAR(190) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_8D93D649E7927C74` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `api_key`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_key` ;

CREATE TABLE IF NOT EXISTS `api_key` (
  `id` VARCHAR(32) NOT NULL,
  `owner_id` INT(11) NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `credential_hash` VARCHAR(60) NOT NULL,
  `last_ip` VARBINARY(16) NULL DEFAULT NULL COMMENT '(DC2Type:ip_address)',
  `last_accessed` DATETIME NULL DEFAULT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_C912ED9D7E3C61F9` (`owner_id` ASC),
  CONSTRAINT `FK_C912ED9D7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `asset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asset` ;

CREATE TABLE IF NOT EXISTS `asset` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `media_type` VARCHAR(255) NOT NULL,
  `storage_id` VARCHAR(190) NOT NULL,
  `extension` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_2AF5A5C5CC5DB90` (`storage_id` ASC),
  INDEX `IDX_2AF5A5C7E3C61F9` (`owner_id` ASC),
  CONSTRAINT `FK_2AF5A5C7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `contrat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contrat` ;

CREATE TABLE IF NOT EXISTS `contrat` (
  `id_contrat` INT(11) NOT NULL AUTO_INCREMENT,
  `cont_type` VARCHAR(45) NULL DEFAULT NULL,
  `cont_statut` VARCHAR(45) NULL DEFAULT NULL,
  `cont_debut` DATE NULL DEFAULT NULL,
  `cont_fin` DATE NULL DEFAULT NULL,
  `cont_heure` VARCHAR(45) NULL DEFAULT NULL,
  `cont_taux` FLOAT NULL DEFAULT NULL,
  `recruteur_id_recruteur` INT(11) NOT NULL,
  PRIMARY KEY (`id_contrat`),
  INDEX `fk_contrat_recruteur1_idx` (`recruteur_id_recruteur` ASC),
  CONSTRAINT `fk_contrat_recruteur1`
    FOREIGN KEY (`recruteur_id_recruteur`)
    REFERENCES `recruteur` (`id_recruteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bulletin_paie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bulletin_paie` ;

CREATE TABLE IF NOT EXISTS `bulletin_paie` (
  `id_bulletin_paie` INT(11) NOT NULL,
  `bul_brut` FLOAT NULL DEFAULT NULL,
  `bul_debut` DATE NULL DEFAULT NULL,
  `bul_fin` DATE NULL DEFAULT NULL,
  `bul_numero` INT(11) NULL DEFAULT NULL,
  `contrat_id_contrat` INT(11) NOT NULL,
  PRIMARY KEY (`id_bulletin_paie`),
  INDEX `fk_bulletin_paie_contrat1_idx` (`contrat_id_contrat` ASC),
  CONSTRAINT `fk_bulletin_paie_contrat1`
    FOREIGN KEY (`contrat_id_contrat`)
    REFERENCES `contrat` (`id_contrat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fulltext_search`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fulltext_search` ;

CREATE TABLE IF NOT EXISTS `fulltext_search` (
  `id` INT(11) NOT NULL,
  `resource` VARCHAR(190) NOT NULL,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `is_public` TINYINT(1) NOT NULL,
  `title` LONGTEXT NULL DEFAULT NULL,
  `text` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `resource`),
  INDEX `IDX_AA31FE4A7E3C61F9` (`owner_id` ASC),
  FULLTEXT INDEX `IDX_AA31FE4A2B36786B3B8BA7C7` (`title`, `text`),
  CONSTRAINT `FK_AA31FE4A7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vocabulary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vocabulary` ;

CREATE TABLE IF NOT EXISTS `vocabulary` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `namespace_uri` VARCHAR(190) NOT NULL,
  `prefix` VARCHAR(190) NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `comment` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_9099C97B9B267FDF` (`namespace_uri` ASC),
  UNIQUE INDEX `UNIQ_9099C97B93B1868E` (`prefix` ASC),
  INDEX `IDX_9099C97B7E3C61F9` (`owner_id` ASC),
  CONSTRAINT `FK_9099C97B7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `resource_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_class` ;

CREATE TABLE IF NOT EXISTS `resource_class` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `vocabulary_id` INT(11) NOT NULL,
  `local_name` VARCHAR(190) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `comment` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_C6F063ADAD0E05F6623C14D5` (`vocabulary_id` ASC, `local_name` ASC),
  INDEX `IDX_C6F063AD7E3C61F9` (`owner_id` ASC),
  INDEX `IDX_C6F063ADAD0E05F6` (`vocabulary_id` ASC),
  CONSTRAINT `FK_C6F063AD7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_C6F063ADAD0E05F6`
    FOREIGN KEY (`vocabulary_id`)
    REFERENCES `vocabulary` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 150
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `property` ;

CREATE TABLE IF NOT EXISTS `property` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `vocabulary_id` INT(11) NOT NULL,
  `local_name` VARCHAR(190) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `comment` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_8BF21CDEAD0E05F6623C14D5` (`vocabulary_id` ASC, `local_name` ASC),
  INDEX `IDX_8BF21CDE7E3C61F9` (`owner_id` ASC),
  INDEX `IDX_8BF21CDEAD0E05F6` (`vocabulary_id` ASC),
  CONSTRAINT `FK_8BF21CDE7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_8BF21CDEAD0E05F6`
    FOREIGN KEY (`vocabulary_id`)
    REFERENCES `vocabulary` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 280
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `resource_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_template` ;

CREATE TABLE IF NOT EXISTS `resource_template` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `resource_class_id` INT(11) NULL DEFAULT NULL,
  `title_property_id` INT(11) NULL DEFAULT NULL,
  `description_property_id` INT(11) NULL DEFAULT NULL,
  `label` VARCHAR(190) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_39ECD52EEA750E8` (`label` ASC),
  INDEX `IDX_39ECD52E7E3C61F9` (`owner_id` ASC),
  INDEX `IDX_39ECD52E448CC1BD` (`resource_class_id` ASC),
  INDEX `IDX_39ECD52E724734A3` (`title_property_id` ASC),
  INDEX `IDX_39ECD52EB84E0D1D` (`description_property_id` ASC),
  CONSTRAINT `FK_39ECD52E448CC1BD`
    FOREIGN KEY (`resource_class_id`)
    REFERENCES `resource_class` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_39ECD52E724734A3`
    FOREIGN KEY (`title_property_id`)
    REFERENCES `property` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_39ECD52E7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_39ECD52EB84E0D1D`
    FOREIGN KEY (`description_property_id`)
    REFERENCES `property` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource` ;

CREATE TABLE IF NOT EXISTS `resource` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `resource_class_id` INT(11) NULL DEFAULT NULL,
  `resource_template_id` INT(11) NULL DEFAULT NULL,
  `thumbnail_id` INT(11) NULL DEFAULT NULL,
  `title` LONGTEXT NULL DEFAULT NULL,
  `is_public` TINYINT(1) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `resource_type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_BC91F4167E3C61F9` (`owner_id` ASC),
  INDEX `IDX_BC91F416448CC1BD` (`resource_class_id` ASC),
  INDEX `IDX_BC91F41616131EA` (`resource_template_id` ASC),
  INDEX `IDX_BC91F416FDFF2E92` (`thumbnail_id` ASC),
  CONSTRAINT `FK_BC91F41616131EA`
    FOREIGN KEY (`resource_template_id`)
    REFERENCES `resource_template` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_BC91F416448CC1BD`
    FOREIGN KEY (`resource_class_id`)
    REFERENCES `resource_class` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_BC91F4167E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_BC91F416FDFF2E92`
    FOREIGN KEY (`thumbnail_id`)
    REFERENCES `asset` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item` ;

CREATE TABLE IF NOT EXISTS `item` (
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_1F1B251EBF396750`
    FOREIGN KEY (`id`)
    REFERENCES `resource` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `item_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_set` ;

CREATE TABLE IF NOT EXISTS `item_set` (
  `id` INT(11) NOT NULL,
  `is_open` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_1015EEEBF396750`
    FOREIGN KEY (`id`)
    REFERENCES `resource` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `item_item_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_item_set` ;

CREATE TABLE IF NOT EXISTS `item_item_set` (
  `item_id` INT(11) NOT NULL,
  `item_set_id` INT(11) NOT NULL,
  PRIMARY KEY (`item_id`, `item_set_id`),
  INDEX `IDX_6D0C9625126F525E` (`item_id` ASC),
  INDEX `IDX_6D0C9625960278D7` (`item_set_id` ASC),
  CONSTRAINT `FK_6D0C9625126F525E`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_6D0C9625960278D7`
    FOREIGN KEY (`item_set_id`)
    REFERENCES `item_set` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `site_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site_page` ;

CREATE TABLE IF NOT EXISTS `site_page` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `site_id` INT(11) NOT NULL,
  `slug` VARCHAR(190) NOT NULL,
  `title` VARCHAR(190) NOT NULL,
  `is_public` TINYINT(1) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_2F900BD9F6BD1646989D9B62` (`site_id` ASC, `slug` ASC),
  INDEX `IDX_2F900BD9F6BD1646` (`site_id` ASC),
  CONSTRAINT `FK_2F900BD9F6BD1646`
    FOREIGN KEY (`site_id`)
    REFERENCES `site` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site` ;

CREATE TABLE IF NOT EXISTS `site` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `homepage_id` INT(11) NULL DEFAULT NULL,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `slug` VARCHAR(190) NOT NULL,
  `theme` VARCHAR(190) NOT NULL,
  `title` VARCHAR(190) NOT NULL,
  `summary` LONGTEXT NULL DEFAULT NULL,
  `navigation` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  `item_pool` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `is_public` TINYINT(1) NOT NULL,
  `assign_new_items` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_694309E4989D9B62` (`slug` ASC),
  UNIQUE INDEX `UNIQ_694309E4571EDDA` (`homepage_id` ASC),
  INDEX `IDX_694309E47E3C61F9` (`owner_id` ASC),
  CONSTRAINT `FK_694309E4571EDDA`
    FOREIGN KEY (`homepage_id`)
    REFERENCES `site_page` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_694309E47E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `item_site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_site` ;

CREATE TABLE IF NOT EXISTS `item_site` (
  `item_id` INT(11) NOT NULL,
  `site_id` INT(11) NOT NULL,
  PRIMARY KEY (`item_id`, `site_id`),
  INDEX `IDX_A1734D1F126F525E` (`item_id` ASC),
  INDEX `IDX_A1734D1FF6BD1646` (`site_id` ASC),
  CONSTRAINT `FK_A1734D1F126F525E`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_A1734D1FF6BD1646`
    FOREIGN KEY (`site_id`)
    REFERENCES `site` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `job` ;

CREATE TABLE IF NOT EXISTS `job` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `pid` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `class` VARCHAR(255) NOT NULL,
  `args` LONGTEXT NULL DEFAULT NULL COMMENT '(DC2Type:json_array)',
  `log` LONGTEXT NULL DEFAULT NULL,
  `started` DATETIME NOT NULL,
  `ended` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_FBD8E0F87E3C61F9` (`owner_id` ASC),
  CONSTRAINT `FK_FBD8E0F87E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `media` ;

CREATE TABLE IF NOT EXISTS `media` (
  `id` INT(11) NOT NULL,
  `item_id` INT(11) NOT NULL,
  `ingester` VARCHAR(255) NOT NULL,
  `renderer` VARCHAR(255) NOT NULL,
  `data` LONGTEXT NULL DEFAULT NULL COMMENT '(DC2Type:json_array)',
  `source` LONGTEXT NULL DEFAULT NULL,
  `media_type` VARCHAR(255) NULL DEFAULT NULL,
  `storage_id` VARCHAR(190) NULL DEFAULT NULL,
  `extension` VARCHAR(255) NULL DEFAULT NULL,
  `sha256` CHAR(64) NULL DEFAULT NULL,
  `size` BIGINT(20) NULL DEFAULT NULL,
  `has_original` TINYINT(1) NOT NULL,
  `has_thumbnails` TINYINT(1) NOT NULL,
  `position` INT(11) NULL DEFAULT NULL,
  `lang` VARCHAR(190) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_6A2CA10C5CC5DB90` (`storage_id` ASC),
  INDEX `IDX_6A2CA10C126F525E` (`item_id` ASC),
  INDEX `item_position` (`item_id` ASC, `position` ASC),
  CONSTRAINT `FK_6A2CA10C126F525E`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`),
  CONSTRAINT `FK_6A2CA10CBF396750`
    FOREIGN KEY (`id`)
    REFERENCES `resource` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `migration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `migration` ;

CREATE TABLE IF NOT EXISTS `migration` (
  `version` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `module` ;

CREATE TABLE IF NOT EXISTS `module` (
  `id` VARCHAR(190) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `version` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `password_creation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `password_creation` ;

CREATE TABLE IF NOT EXISTS `password_creation` (
  `id` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `activate` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_C77917B4A76ED395` (`user_id` ASC),
  CONSTRAINT `FK_C77917B4A76ED395`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patient` ;

CREATE TABLE IF NOT EXISTS `patient` (
  `id_patient` INT(11) NOT NULL AUTO_INCREMENT,
  `pa_nom` VARCHAR(45) NULL DEFAULT NULL,
  `pa_date_naissance` DATE NULL DEFAULT NULL,
  `pa_num_secu` VARCHAR(45) NULL DEFAULT NULL,
  `pa_tel` VARCHAR(45) NULL DEFAULT NULL,
  `pa_mail` VARCHAR(45) NULL DEFAULT NULL,
  `pa_adresse` VARCHAR(45) NULL DEFAULT NULL,
  `pa_ville` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_patient`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rendez_vous`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rendez_vous` ;

CREATE TABLE IF NOT EXISTS `rendez_vous` (
  `id_rendez_vous` INT(11) NOT NULL AUTO_INCREMENT,
  `rv_date` DATE NULL DEFAULT NULL,
  `rv_heure` TIME NULL DEFAULT NULL,
  `patient_id_patient` INT(11) NOT NULL,
  PRIMARY KEY (`id_rendez_vous`),
  INDEX `fk_rendez_vous_patient_idx` (`patient_id_patient` ASC),
  CONSTRAINT `fk_rendez_vous_patient`
    FOREIGN KEY (`patient_id_patient`)
    REFERENCES `patient` (`id_patient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resource_template_property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource_template_property` ;

CREATE TABLE IF NOT EXISTS `resource_template_property` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `resource_template_id` INT(11) NOT NULL,
  `property_id` INT(11) NOT NULL,
  `alternate_label` VARCHAR(255) NULL DEFAULT NULL,
  `alternate_comment` LONGTEXT NULL DEFAULT NULL,
  `position` INT(11) NULL DEFAULT NULL,
  `data_type` LONGTEXT NULL DEFAULT NULL COMMENT '(DC2Type:json_array)',
  `is_required` TINYINT(1) NOT NULL,
  `is_private` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_4689E2F116131EA549213EC` (`resource_template_id` ASC, `property_id` ASC),
  INDEX `IDX_4689E2F116131EA` (`resource_template_id` ASC),
  INDEX `IDX_4689E2F1549213EC` (`property_id` ASC),
  CONSTRAINT `FK_4689E2F116131EA`
    FOREIGN KEY (`resource_template_id`)
    REFERENCES `resource_template` (`id`),
  CONSTRAINT `FK_4689E2F1549213EC`
    FOREIGN KEY (`property_id`)
    REFERENCES `property` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 134
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session` ;

CREATE TABLE IF NOT EXISTS `session` (
  `id` VARCHAR(190) NOT NULL,
  `data` LONGBLOB NOT NULL,
  `modified` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `setting` ;

CREATE TABLE IF NOT EXISTS `setting` (
  `id` VARCHAR(190) NOT NULL,
  `value` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `site_page_block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site_page_block` ;

CREATE TABLE IF NOT EXISTS `site_page_block` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `page_id` INT(11) NOT NULL,
  `layout` VARCHAR(80) NOT NULL,
  `data` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  `position` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_C593E731C4663E4` (`page_id` ASC),
  INDEX `page_position` (`page_id` ASC, `position` ASC),
  CONSTRAINT `FK_C593E731C4663E4`
    FOREIGN KEY (`page_id`)
    REFERENCES `site_page` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `site_block_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site_block_attachment` ;

CREATE TABLE IF NOT EXISTS `site_block_attachment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `block_id` INT(11) NOT NULL,
  `item_id` INT(11) NULL DEFAULT NULL,
  `media_id` INT(11) NULL DEFAULT NULL,
  `caption` LONGTEXT NOT NULL,
  `position` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_236473FEE9ED820C` (`block_id` ASC),
  INDEX `IDX_236473FE126F525E` (`item_id` ASC),
  INDEX `IDX_236473FEEA9FDD75` (`media_id` ASC),
  INDEX `block_position` (`block_id` ASC, `position` ASC),
  CONSTRAINT `FK_236473FE126F525E`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_236473FEE9ED820C`
    FOREIGN KEY (`block_id`)
    REFERENCES `site_page_block` (`id`),
  CONSTRAINT `FK_236473FEEA9FDD75`
    FOREIGN KEY (`media_id`)
    REFERENCES `media` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `site_item_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site_item_set` ;

CREATE TABLE IF NOT EXISTS `site_item_set` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `site_id` INT(11) NOT NULL,
  `item_set_id` INT(11) NOT NULL,
  `position` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_D4CE134F6BD1646960278D7` (`site_id` ASC, `item_set_id` ASC),
  INDEX `IDX_D4CE134F6BD1646` (`site_id` ASC),
  INDEX `IDX_D4CE134960278D7` (`item_set_id` ASC),
  INDEX `position` (`position` ASC),
  CONSTRAINT `FK_D4CE134960278D7`
    FOREIGN KEY (`item_set_id`)
    REFERENCES `item_set` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_D4CE134F6BD1646`
    FOREIGN KEY (`site_id`)
    REFERENCES `site` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `site_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site_permission` ;

CREATE TABLE IF NOT EXISTS `site_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `site_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `role` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_C0401D6FF6BD1646A76ED395` (`site_id` ASC, `user_id` ASC),
  INDEX `IDX_C0401D6FF6BD1646` (`site_id` ASC),
  INDEX `IDX_C0401D6FA76ED395` (`user_id` ASC),
  CONSTRAINT `FK_C0401D6FA76ED395`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_C0401D6FF6BD1646`
    FOREIGN KEY (`site_id`)
    REFERENCES `site` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `site_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site_setting` ;

CREATE TABLE IF NOT EXISTS `site_setting` (
  `id` VARCHAR(190) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `value` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  PRIMARY KEY (`id`, `site_id`),
  INDEX `IDX_64D05A53F6BD1646` (`site_id` ASC),
  CONSTRAINT `FK_64D05A53F6BD1646`
    FOREIGN KEY (`site_id`)
    REFERENCES `site` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test` ;

CREATE TABLE IF NOT EXISTS `test` (
  `id_test` INT(11) NOT NULL AUTO_INCREMENT,
  `te_ref` INT(11) NULL DEFAULT NULL,
  `te_date` DATE NULL DEFAULT NULL,
  `te_resultat` VARCHAR(45) NULL DEFAULT NULL,
  `rendez_vous_id_rendez_vous` INT(11) NOT NULL,
  PRIMARY KEY (`id_test`),
  INDEX `fk_test_rendez_vous1_idx` (`rendez_vous_id_rendez_vous` ASC),
  CONSTRAINT `fk_test_rendez_vous1`
    FOREIGN KEY (`rendez_vous_id_rendez_vous`)
    REFERENCES `rendez_vous` (`id_rendez_vous`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `user_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_setting` ;

CREATE TABLE IF NOT EXISTS `user_setting` (
  `id` VARCHAR(190) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `value` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  PRIMARY KEY (`id`, `user_id`),
  INDEX `IDX_C779A692A76ED395` (`user_id` ASC),
  CONSTRAINT `FK_C779A692A76ED395`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `value` ;

CREATE TABLE IF NOT EXISTS `value` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `resource_id` INT(11) NOT NULL,
  `property_id` INT(11) NOT NULL,
  `value_resource_id` INT(11) NULL DEFAULT NULL,
  `type` VARCHAR(255) NOT NULL,
  `lang` VARCHAR(255) NULL DEFAULT NULL,
  `value` LONGTEXT NULL DEFAULT NULL,
  `uri` LONGTEXT NULL DEFAULT NULL,
  `is_public` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_1D77583489329D25` (`resource_id` ASC),
  INDEX `IDX_1D775834549213EC` (`property_id` ASC),
  INDEX `IDX_1D7758344BC72506` (`value_resource_id` ASC),
  INDEX `value` (`value`(190) ASC),
  INDEX `uri` (`uri`(190) ASC),
  CONSTRAINT `FK_1D7758344BC72506`
    FOREIGN KEY (`value_resource_id`)
    REFERENCES `resource` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_1D775834549213EC`
    FOREIGN KEY (`property_id`)
    REFERENCES `property` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_1D77583489329D25`
    FOREIGN KEY (`resource_id`)
    REFERENCES `resource` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
