-- MySQL Script generated by MySQL Workbench
-- Tue May  4 14:47:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patient` ;

CREATE TABLE IF NOT EXISTS `patient` (
  `id_patient` INT NOT NULL AUTO_INCREMENT,
  `pa_nom` VARCHAR(45) NULL,
  `pa_date_naissance` DATE NULL,
  `pa_num_secu` VARCHAR(45) NULL,
  `pa_tel` VARCHAR(45) NULL,
  `pa_mail` VARCHAR(45) NULL,
  `pa_adresse` VARCHAR(45) NULL,
  `pa_ville` VARCHAR(45) NULL,
  PRIMARY KEY (`id_patient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rendez_vous`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rendez_vous` ;

CREATE TABLE IF NOT EXISTS `rendez_vous` (
  `id_rendez_vous` INT NOT NULL AUTO_INCREMENT,
  `rv_date` DATE NULL,
  `rv_heure` TIME NULL,
  `patient_id_patient` INT NOT NULL,
  PRIMARY KEY (`id_rendez_vous`),
  INDEX `fk_rendez_vous_patient_idx` (`patient_id_patient` ASC),
  CONSTRAINT `fk_rendez_vous_patient`
    FOREIGN KEY (`patient_id_patient`)
    REFERENCES `patient` (`id_patient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test` ;

CREATE TABLE IF NOT EXISTS `test` (
  `id_test` INT NOT NULL AUTO_INCREMENT,
  `te_date` DATE NULL,
  `te_heure` TIME NULL,
  `te_resultat` VARCHAR(45) NULL,
  `rendez_vous_id_rendez_vous` INT NOT NULL,
  PRIMARY KEY (`id_test`),
  INDEX `fk_test_rendez_vous1_idx` (`rendez_vous_id_rendez_vous` ASC),
  CONSTRAINT `fk_test_rendez_vous1`
    FOREIGN KEY (`rendez_vous_id_rendez_vous`)
    REFERENCES `rendez_vous` (`id_rendez_vous`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock` ;

CREATE TABLE IF NOT EXISTS `stock` (
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `test_id_test` INT NOT NULL,
  `st_quantite_initial` INT NOT NULL DEFAULT '2000',
  `st_quantite_maj` INT GENERATED ALWAYS AS (st_quantite_initial - test_id_test) VIRTUAL,
  PRIMARY KEY (`id_stock`),
  INDEX `fk_stock_test1_idx` (`test_id_test` ASC),
  CONSTRAINT `fk_stock_test1`
    FOREIGN KEY (`test_id_test`)
    REFERENCES `test` (`id_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
