-- MySQL Script generated by MySQL Workbench
-- Thu Apr 29 17:53:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema donateur_db
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `coor_ban`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coor_ban` ;

CREATE TABLE IF NOT EXISTS `coor_ban` (
  `id_coor_ban` INT NOT NULL AUTO_INCREMENT,
  `coor_banc_ib` VARCHAR(45) NULL,
  `coor_banc_bi` VARCHAR(45) NULL,
  PRIMARY KEY (`id_coor_ban`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact` ;

CREATE TABLE IF NOT EXISTS `contact` (
  `id_contact` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `code_postal` INT NULL,
  `tel` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id_contact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `donateur` ;

CREATE TABLE IF NOT EXISTS `donateur` (
  `id_donateur` INT NOT NULL AUTO_INCREMENT,
  `don_type` VARCHAR(45) NULL,
  `don_nom` VARCHAR(45) NULL,
  `don_prenom` VARCHAR(45) NULL,
  `don_genre` VARCHAR(45) NULL,
  `don_naissance` DATE NULL,
  `coor_ban_id_coor_ban` INT NOT NULL,
  `contact_id_contact` INT NOT NULL,
  PRIMARY KEY (`id_donateur`),
  INDEX `fk_donateur_coor_ban1_idx` (`coor_ban_id_coor_ban` ASC),
  INDEX `fk_donateur_contact1_idx` (`contact_id_contact` ASC),
  CONSTRAINT `fk_donateur_coor_ban1`
    FOREIGN KEY (`coor_ban_id_coor_ban`)
    REFERENCES `coor_ban` (`id_coor_ban`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_donateur_contact1`
    FOREIGN KEY (`contact_id_contact`)
    REFERENCES `contact` (`id_contact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coor_ban_rec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coor_ban_rec` ;

CREATE TABLE IF NOT EXISTS `coor_ban_rec` (
  `id_coor_ban_rec` INT NOT NULL,
  `coor_banc_ib_rec` VARCHAR(45) NULL,
  `coor_banc_bi_rec` VARCHAR(45) NULL,
  PRIMARY KEY (`id_coor_ban_rec`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recruteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruteur` ;

CREATE TABLE IF NOT EXISTS `recruteur` (
  `id_recruteur` INT NOT NULL AUTO_INCREMENT,
  `rec_nom` VARCHAR(45) NULL,
  `rec_prenom` VARCHAR(45) NULL,
  `rec_naissance` DATE NULL,
  `rec_statut` VARCHAR(45) NULL,
  `rec_heure_t` FLOAT NULL,
  `rec_heure_r` FLOAT NULL,
  `rec_numero_secu` VARCHAR(45) NULL,
  `contact_id_contact` INT NOT NULL,
  `coor_ban_rec_id_coor_ban_rec` INT NOT NULL,
  PRIMARY KEY (`id_recruteur`),
  INDEX `fk_recruteur_contact1_idx` (`contact_id_contact` ASC),
  INDEX `fk_recruteur_coor_ban_rec1_idx` (`coor_ban_rec_id_coor_ban_rec` ASC),
  CONSTRAINT `fk_recruteur_contact1`
    FOREIGN KEY (`contact_id_contact`)
    REFERENCES `contact` (`id_contact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recruteur_coor_ban_rec1`
    FOREIGN KEY (`coor_ban_rec_id_coor_ban_rec`)
    REFERENCES `coor_ban_rec` (`id_coor_ban_rec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `association`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `association` ;

CREATE TABLE IF NOT EXISTS `association` (
  `id_association` INT NOT NULL AUTO_INCREMENT,
  `ass_nom` VARCHAR(45) NULL,
  `ass_statut` VARCHAR(45) NULL,
  `ass_heure_recrut` FLOAT NULL,
  `contact_id_contact` INT NOT NULL,
  PRIMARY KEY (`id_association`),
  INDEX `fk_association_contact1_idx` (`contact_id_contact` ASC),
  CONSTRAINT `fk_association_contact1`
    FOREIGN KEY (`contact_id_contact`)
    REFERENCES `contact` (`id_contact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contrat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contrat` ;

CREATE TABLE IF NOT EXISTS `contrat` (
  `id_contrat` INT NOT NULL AUTO_INCREMENT,
  `cont_type` VARCHAR(45) NULL,
  `cont_statut` VARCHAR(45) NULL,
  `cont_debut` DATE NULL,
  `cont_fin` DATE NULL,
  `cont_heure` VARCHAR(45) NULL,
  `cont_taux` FLOAT NULL,
  `recruteur_id_recruteur` INT NOT NULL,
  PRIMARY KEY (`id_contrat`),
  INDEX `fk_contrat_recruteur1_idx` (`recruteur_id_recruteur` ASC),
  CONSTRAINT `fk_contrat_recruteur1`
    FOREIGN KEY (`recruteur_id_recruteur`)
    REFERENCES `recruteur` (`id_recruteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bulletin_paie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bulletin_paie` ;

CREATE TABLE IF NOT EXISTS `bulletin_paie` (
  `id_bulletin_paie` INT NOT NULL,
  `bul_brut` FLOAT NULL,
  `bul_debut` DATE NULL,
  `bul_fin` DATE NULL,
  `bul_numero` INT NULL,
  `contrat_id_contrat` INT NOT NULL,
  PRIMARY KEY (`id_bulletin_paie`),
  INDEX `fk_bulletin_paie_contrat1_idx` (`contrat_id_contrat` ASC),
  CONSTRAINT `fk_bulletin_paie_contrat1`
    FOREIGN KEY (`contrat_id_contrat`)
    REFERENCES `contrat` (`id_contrat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adhesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adhesion` ;

CREATE TABLE IF NOT EXISTS `adhesion` (
  `id_adhesion` INT NOT NULL AUTO_INCREMENT,
  `ad_montant` INT NULL,
  `ad_statut` VARCHAR(45) NULL,
  `ad_date_debut` DATE NULL,
  `ad_date_fin` DATE NULL,
  `association_id_association` INT NOT NULL,
  `donateur_id_donateur` INT NOT NULL,
  `recruteur_id_recruteur` INT NOT NULL,
  PRIMARY KEY (`id_adhesion`),
  INDEX `fk_adhesion_association1_idx` (`association_id_association` ASC),
  INDEX `fk_adhesion_donateur1_idx` (`donateur_id_donateur` ASC),
  INDEX `fk_adhesion_recruteur1_idx` (`recruteur_id_recruteur` ASC),
  CONSTRAINT `fk_adhesion_association1`
    FOREIGN KEY (`association_id_association`)
    REFERENCES `association` (`id_association`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adhesion_donateur1`
    FOREIGN KEY (`donateur_id_donateur`)
    REFERENCES `donateur` (`id_donateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adhesion_recruteur1`
    FOREIGN KEY (`recruteur_id_recruteur`)
    REFERENCES `recruteur` (`id_recruteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
