-- MySQL Script generated by MySQL Workbench
-- Thu Mar 18 16:10:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articles` (
  `id_articles` INT NOT NULL AUTO_INCREMENT,
  `prix_unitaire` INT NULL,
  `designation_article` VARCHAR(45) NULL,
  PRIMARY KEY (`id_articles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commander`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commander` (
  `id_Commander` INT NOT NULL AUTO_INCREMENT,
  `quantite_commandee` INT NULL,
  `date_commande` VARCHAR(45) NULL,
  `Articles_id_articles` INT NOT NULL,
  PRIMARY KEY (`id_Commander`, `Articles_id_articles`),
  CONSTRAINT `fk_Commander_Articles1`
    FOREIGN KEY (`Articles_id_articles`)
    REFERENCES `mydb`.`Articles` (`id_articles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Commander_Articles1_idx` ON `mydb`.`Commander` (`Articles_id_articles` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `id_numero_client` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `adresse_client` VARCHAR(45) NULL,
  `numero_client` INT NULL,
  `Commander_id_Commander` INT NOT NULL,
  PRIMARY KEY (`id_numero_client`, `Commander_id_Commander`),
  CONSTRAINT `fk_Client_Commander1`
    FOREIGN KEY (`Commander_id_Commander`)
    REFERENCES `mydb`.`Commander` (`id_Commander`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Client_Commander1_idx` ON `mydb`.`Client` (`Commander_id_Commander` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fournisseur` (
  `id_Fournisseur` INT NOT NULL AUTO_INCREMENT,
  `numero_fournisseur` INT NULL,
  `nom_contact` VARCHAR(45) NULL,
  `numero_telephone_contact` INT NULL,
  PRIMARY KEY (`id_Fournisseur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livrer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livrer` (
  `id_Livraison` INT NOT NULL AUTO_INCREMENT,
  `quantite_livree` INT NULL,
  `date_livraison` VARCHAR(45) NULL,
  `nom_livreur` VARCHAR(45) NULL,
  `Articles_id_articles` INT NOT NULL,
  `Fournisseur_id_Fournisseur` INT NOT NULL,
  PRIMARY KEY (`id_Livraison`, `Articles_id_articles`, `Fournisseur_id_Fournisseur`),
  CONSTRAINT `fk_Livrer_Articles1`
    FOREIGN KEY (`Articles_id_articles`)
    REFERENCES `mydb`.`Articles` (`id_articles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livrer_Fournisseur1`
    FOREIGN KEY (`Fournisseur_id_Fournisseur`)
    REFERENCES `mydb`.`Fournisseur` (`id_Fournisseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Livrer_Articles1_idx` ON `mydb`.`Livrer` (`Articles_id_articles` ASC) VISIBLE;

CREATE INDEX `fk_Livrer_Fournisseur1_idx` ON `mydb`.`Livrer` (`Fournisseur_id_Fournisseur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Articles_has_Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articles_has_Client` (
  `Articles_id_articles` INT NOT NULL,
  `Client_id_numero_client` INT NOT NULL,
  PRIMARY KEY (`Articles_id_articles`, `Client_id_numero_client`),
  CONSTRAINT `fk_Articles_has_Client_Articles1`
    FOREIGN KEY (`Articles_id_articles`)
    REFERENCES `mydb`.`Articles` (`id_articles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Client_Client1`
    FOREIGN KEY (`Client_id_numero_client`)
    REFERENCES `mydb`.`Client` (`id_numero_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Articles_has_Client_Client1_idx` ON `mydb`.`Articles_has_Client` (`Client_id_numero_client` ASC) VISIBLE;

CREATE INDEX `fk_Articles_has_Client_Articles1_idx` ON `mydb`.`Articles_has_Client` (`Articles_id_articles` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
