-- MySQL Script generated by MySQL Workbench
-- Sat Mar 20 12:14:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Magasin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Magasin` (
  `id_Magasin` INT NOT NULL AUTO_INCREMENT,
  `Nom_magasin` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Magasin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `id_Client` INT NOT NULL AUTO_INCREMENT,
  `Nom_Client` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Magasin_has_Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Magasin_has_Client` (
  `Magasin_id_Magasin` INT NOT NULL,
  `Client_id_Client` INT NOT NULL,
  PRIMARY KEY (`Magasin_id_Magasin`, `Client_id_Client`),
  INDEX `fk_Magasin_has_Client_Client1_idx` (`Client_id_Client` ASC) VISIBLE,
  INDEX `fk_Magasin_has_Client_Magasin_idx` (`Magasin_id_Magasin` ASC) VISIBLE,
  CONSTRAINT `fk_Magasin_has_Client_Magasin`
    FOREIGN KEY (`Magasin_id_Magasin`)
    REFERENCES `mydb`.`Magasin` (`id_Magasin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Magasin_has_Client_Client1`
    FOREIGN KEY (`Client_id_Client`)
    REFERENCES `mydb`.`Client` (`id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articles` (
  `id_Articles` INT NOT NULL AUTO_INCREMENT,
  `Numero_Article` VARCHAR(45) NULL,
  `Magasin_id_Magasin` INT NOT NULL,
  PRIMARY KEY (`id_Articles`, `Magasin_id_Magasin`),
  INDEX `fk_Articles_Magasin1_idx` (`Magasin_id_Magasin` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_Magasin1`
    FOREIGN KEY (`Magasin_id_Magasin`)
    REFERENCES `mydb`.`Magasin` (`id_Magasin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
