-- MySQL Script generated by MySQL Workbench
-- Tue May  4 10:13:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdd_examen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_examen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd_examen` DEFAULT CHARACTER SET utf8 ;
USE `bdd_examen` ;

-- -----------------------------------------------------
-- Table `bdd_examen`.`Centre_de_Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdd_examen`.`Centre_de_Test` ;

CREATE TABLE IF NOT EXISTS `bdd_examen`.`Centre_de_Test` (
  `idSeance` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  PRIMARY KEY (`idSeance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_examen`.`Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdd_examen`.`Test` ;

CREATE TABLE IF NOT EXISTS `bdd_examen`.`Test` (
  `id_test` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `date_dispo` DATE NULL,
  PRIMARY KEY (`id_test`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_examen`.`Individu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdd_examen`.`Individu` ;

CREATE TABLE IF NOT EXISTS `bdd_examen`.`Individu` (
  `id_individu` INT NOT NULL AUTO_INCREMENT,
  `sexe` VARCHAR(45) NULL,
  `age` INT NULL,
  `date_rdv_test` DATE NULL,
  PRIMARY KEY (`id_individu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_examen`.`Tested_Individu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdd_examen`.`Tested_Individu` ;

CREATE TABLE IF NOT EXISTS `bdd_examen`.`Tested_Individu` (
  `id_testedindividu` INT NOT NULL AUTO_INCREMENT,
  `sexe` VARCHAR(45) NULL,
  `age` INT NULL,
  `date_tested` DATE NULL,
  PRIMARY KEY (`id_testedindividu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_examen`.`Centre_de_Test_has_Individu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdd_examen`.`Centre_de_Test_has_Individu` ;

CREATE TABLE IF NOT EXISTS `bdd_examen`.`Centre_de_Test_has_Individu` (
  `Centre_de_Test_idSeance` INT NOT NULL,
  `Individu_id_individu` INT NOT NULL,
  PRIMARY KEY (`Centre_de_Test_idSeance`, `Individu_id_individu`),
  INDEX `fk_Centre_de_Test_has_Individu_Individu1_idx` (`Individu_id_individu` ASC),
  INDEX `fk_Centre_de_Test_has_Individu_Centre_de_Test_idx` (`Centre_de_Test_idSeance` ASC),
  CONSTRAINT `fk_Centre_de_Test_has_Individu_Centre_de_Test`
    FOREIGN KEY (`Centre_de_Test_idSeance`)
    REFERENCES `bdd_examen`.`Centre_de_Test` (`idSeance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Centre_de_Test_has_Individu_Individu1`
    FOREIGN KEY (`Individu_id_individu`)
    REFERENCES `bdd_examen`.`Individu` (`id_individu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_examen`.`Centre_de_Test_has_Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdd_examen`.`Centre_de_Test_has_Test` ;

CREATE TABLE IF NOT EXISTS `bdd_examen`.`Centre_de_Test_has_Test` (
  `Centre_de_Test_idSeance` INT NOT NULL,
  `Test_id_test` INT NOT NULL,
  PRIMARY KEY (`Centre_de_Test_idSeance`, `Test_id_test`),
  INDEX `fk_Centre_de_Test_has_Test_Test1_idx` (`Test_id_test` ASC),
  INDEX `fk_Centre_de_Test_has_Test_Centre_de_Test1_idx` (`Centre_de_Test_idSeance` ASC),
  CONSTRAINT `fk_Centre_de_Test_has_Test_Centre_de_Test1`
    FOREIGN KEY (`Centre_de_Test_idSeance`)
    REFERENCES `bdd_examen`.`Centre_de_Test` (`idSeance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Centre_de_Test_has_Test_Test1`
    FOREIGN KEY (`Test_id_test`)
    REFERENCES `bdd_examen`.`Test` (`id_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_examen`.`Centre_de_Test_has_Tested_Individu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdd_examen`.`Centre_de_Test_has_Tested_Individu` ;

CREATE TABLE IF NOT EXISTS `bdd_examen`.`Centre_de_Test_has_Tested_Individu` (
  `Centre_de_Test_idSeance` INT NOT NULL,
  `Tested_Individu_id_testedindividu` INT NOT NULL,
  PRIMARY KEY (`Centre_de_Test_idSeance`, `Tested_Individu_id_testedindividu`),
  INDEX `fk_Centre_de_Test_has_Tested_Individu_Tested_Individu1_idx` (`Tested_Individu_id_testedindividu` ASC),
  INDEX `fk_Centre_de_Test_has_Tested_Individu_Centre_de_Test1_idx` (`Centre_de_Test_idSeance` ASC),
  CONSTRAINT `fk_Centre_de_Test_has_Tested_Individu_Centre_de_Test1`
    FOREIGN KEY (`Centre_de_Test_idSeance`)
    REFERENCES `bdd_examen`.`Centre_de_Test` (`idSeance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Centre_de_Test_has_Tested_Individu_Tested_Individu1`
    FOREIGN KEY (`Tested_Individu_id_testedindividu`)
    REFERENCES `bdd_examen`.`Tested_Individu` (`id_testedindividu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
