-- MySQL Script generated by MySQL Workbench
-- Tue May  4 14:26:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `covidtest` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `covidtest` DEFAULT CHARACTER SET utf8 ;
USE `covidtest` ;

-- -----------------------------------------------------
-- Table `mydb`.`Disponibilite_test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `covidtest`.`Disponibilite_test` ;

CREATE TABLE IF NOT EXISTS `covidtest`.`Disponibilite_test` (
  `idDisponibilite_test` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `Heure` TIME(0) NULL,
  `identifiant_infirmier` INT NULL,
  PRIMARY KEY (`idDisponibilite_test`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RendezVous`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `covidtest`.`RendezVous` ;

CREATE TABLE IF NOT EXISTS `covidtest`.`RendezVous` (
  `idRendezVous` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `Heure` TIME(0) NULL,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Present` VARBINARY(1) NULL,
  `idDisponibilite_test` INT NOT NULL,
  PRIMARY KEY (`idRendezVous`, `idDisponibilite_test`),
  CONSTRAINT `fk_RendezVous_Disponibilite_test`
    FOREIGN KEY (`idDisponibilite_test`)
    REFERENCES `covidtest`.`Disponibilite_test` (`idDisponibilite_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personnes_testees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `covidtest`.`Personnes_testees` ;

CREATE TABLE IF NOT EXISTS `covidtest`.`Personnes_testees` (
  `idPersonnes_testees` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Age` DOUBLE NULL,
  `Sexe` VARCHAR(45) NULL,
  `Ville` VARCHAR(45) NULL,
  `rv_idDisponibilite_test` INT NOT NULL,
  PRIMARY KEY (`idPersonnes_testees`, `rv_idDisponibilite_test`),
  CONSTRAINT `fk_Personnes_testees_RendezVous1`
    FOREIGN KEY (`rv_idDisponibilite_test`)
    REFERENCES `covidtest`.`RendezVous` (`idDisponibilite_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`A_un_resultat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `covidtest`.`A_un_resultat` ;

CREATE TABLE IF NOT EXISTS `covidtest`.`A_un_resultat` (
  `idDisponibilite_test` INT NOT NULL,
  PRIMARY KEY (`idDisponibilite_test`),
  CONSTRAINT `fk_La_personne_testee_a_un_resultat_Personnes_testees1`
    FOREIGN KEY (`idDisponibilite_test`)
    REFERENCES `covidtest`.`Personnes_testees` (`rv_idDisponibilite_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resultats_tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `covidtest`.`Resultats_tests` ;

CREATE TABLE IF NOT EXISTS `covidtest`.`Resultats_tests` (
  `idResultats_tests` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Resultat` VARCHAR(15) NULL,
  `idDisponibilite_test` INT NOT NULL,
  PRIMARY KEY (`idResultats_tests`, `idDisponibilite_test`),
  CONSTRAINT `fk_Resultats_tests_La_personne_testee_a_un_resultat1`
    FOREIGN KEY (`idDisponibilite_test`)
    REFERENCES `covidtest`.`A_un_resultat` (`idDisponibilite_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
