-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 20:29:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personne` (
  `idPersonne` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Prénom` VARCHAR(45) NULL,
  `Date_Naiss` DATE NULL,
  PRIMARY KEY (`idPersonne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commune`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commune` (
  `idCommune` INT NOT NULL,
  `Superficie` VARCHAR(45) NULL,
  `Nombre_dhab` INT NULL,
  `Departement` INT NULL,
  `Maire` VARCHAR(45) NULL,
  PRIMARY KEY (`idCommune`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quartier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quartier` (
  `idQuartier` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Superficie` DECIMAL NULL,
  `Commune_idCommune` INT NOT NULL,
  PRIMARY KEY (`idQuartier`, `Commune_idCommune`),
  INDEX `fk_Quartier_Commune1_idx` (`Commune_idCommune` ASC) VISIBLE,
  CONSTRAINT `fk_Quartier_Commune1`
    FOREIGN KEY (`Commune_idCommune`)
    REFERENCES `mydb`.`Commune` (`idCommune`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Immeuble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Immeuble` (
  `idImmeuble` INT NOT NULL,
  `Surface_PC` DECIMAL NULL,
  `Date_Construction` DATE NULL,
  `Etat_PC` DECIMAL NULL,
  `Digicode` VARCHAR(45) NULL,
  `Quartier_idQuartier` INT NOT NULL,
  PRIMARY KEY (`idImmeuble`, `Quartier_idQuartier`),
  INDEX `fk_Immeuble_Quartier1_idx` (`Quartier_idQuartier` ASC) VISIBLE,
  CONSTRAINT `fk_Immeuble_Quartier1`
    FOREIGN KEY (`Quartier_idQuartier`)
    REFERENCES `mydb`.`Quartier` (`idQuartier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appartement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appartement` (
  `idAppartement` INT NOT NULL,
  `Classe_E` VARCHAR(45) NULL,
  `Surface` INT NULL,
  `Nb_Pieces` INT NULL,
  `Nb_Chambres` VARCHAR(45) NULL,
  `Immeuble_idImmeuble1` INT NOT NULL,
  `Immeuble_Quartier_idQuartier` INT NOT NULL,
  PRIMARY KEY (`idAppartement`, `Immeuble_idImmeuble1`, `Immeuble_Quartier_idQuartier`),
  INDEX `fk_Appartement_Immeuble2_idx` (`Immeuble_idImmeuble1` ASC, `Immeuble_Quartier_idQuartier` ASC) VISIBLE,
  CONSTRAINT `fk_Appartement_Immeuble2`
    FOREIGN KEY (`Immeuble_idImmeuble1` , `Immeuble_Quartier_idQuartier`)
    REFERENCES `mydb`.`Immeuble` (`idImmeuble` , `Quartier_idQuartier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personne_has_Appartement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personne_has_Appartement` (
  `Personne_idPersonne` INT NOT NULL,
  `Appartement_idAppartement` INT NOT NULL,
  PRIMARY KEY (`Personne_idPersonne`, `Appartement_idAppartement`),
  INDEX `fk_Personne_has_Appartement_Appartement1_idx` (`Appartement_idAppartement` ASC) VISIBLE,
  INDEX `fk_Personne_has_Appartement_Personne_idx` (`Personne_idPersonne` ASC) VISIBLE,
  CONSTRAINT `fk_Personne_has_Appartement_Personne`
    FOREIGN KEY (`Personne_idPersonne`)
    REFERENCES `mydb`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personne_has_Appartement_Appartement1`
    FOREIGN KEY (`Appartement_idAppartement`)
    REFERENCES `mydb`.`Appartement` (`idAppartement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
