-- MySQL Script generated by MySQL Workbench
-- Tue May  4 11:22:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `rendez_vous`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rendez_vous` (
  `idrendez_vous` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `patient` VARCHAR(45) NULL,
  PRIMARY KEY (`idrendez_vous`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patient` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `date de naissance` DATE NULL,
  `vacciné` TINYINT NULL,
  `comorbidités` INT NULL,
  `rendez_vous_idrendez_vous` INT NOT NULL,
  PRIMARY KEY (`idtable1`, `rendez_vous_idrendez_vous`),
  CONSTRAINT `fk_patient_rendez-vous1`
    FOREIGN KEY (`rendez_vous_idrendez_vous`)
    REFERENCES `rendez_vous` (`idrendez_vous`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test` (
  `idtest` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `disponibilité` INT NULL,
  `utilisé` INT NULL,
  PRIMARY KEY (`idtest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rendez_vous_has_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rendez_vous_has_test` (
  `rendez_vous_idrendez-vous` INT NOT NULL,
  `test_idtest` INT NOT NULL,
  PRIMARY KEY (`rendez_vous_idrendez-vous`, `test_idtest`),
  CONSTRAINT `fk_rendez_vous_has_test_rendez-vous`
    FOREIGN KEY (`rendez_vous_idrendez-vous`)
    REFERENCES `rendez_vous` (`idrendez_vous`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rendez_vous_has_test_test1`
    FOREIGN KEY (`test_idtest`)
    REFERENCES `test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
