-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 09:16:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Contrat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contrat` (
  `id_contrat` INT NOT NULL,
  `cdi_cdd` VARCHAR(45) NULL,
  `salaire` DECIMAL NULL,
  `fk_idEmploye` INT NULL,
  PRIMARY KEY (`id_contrat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Poste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Poste` (
  `idPoste` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `niveau_hierarchique` VARCHAR(45) NULL,
  `fk_idEmploye` INT NULL,
  PRIMARY KEY (`idPoste`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employe` (
  `idEmploye` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `idEntreprise` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `Contrat_id_contrat` INT NOT NULL,
  `Poste_idPoste` INT NOT NULL,
  PRIMARY KEY (`idEmploye`, `Contrat_id_contrat`, `Poste_idPoste`),
  INDEX `fk_Employe_Contrat1_idx` (`Contrat_id_contrat` ASC) VISIBLE,
  INDEX `fk_Employe_Poste1_idx` (`Poste_idPoste` ASC) VISIBLE,
  CONSTRAINT `fk_Employe_Contrat1`
    FOREIGN KEY (`Contrat_id_contrat`)
    REFERENCES `mydb`.`Contrat` (`id_contrat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employe_Poste1`
    FOREIGN KEY (`Poste_idPoste`)
    REFERENCES `mydb`.`Poste` (`idPoste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projet` (
  `idProjet` INT NOT NULL,
  `mission` VARCHAR(45) NULL,
  `durée` DECIMAL(45) NULL,
  `cout` DECIMAL(45) NULL,
  PRIMARY KEY (`idProjet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Site` (
  `id_site` INT NOT NULL,
  `adresse` VARCHAR(45) NULL,
  `CP` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NULL,
  PRIMARY KEY (`id_site`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employe_has_Projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employe_has_Projet` (
  `fk_idEmploye` INT NOT NULL,
  `fk_idProjet` INT NOT NULL,
  PRIMARY KEY (`fk_idEmploye`, `fk_idProjet`),
  INDEX `fk_Employe_has_Projet_Projet1_idx` (`fk_idProjet` ASC) VISIBLE,
  INDEX `fk_Employe_has_Projet_Employe_idx` (`fk_idEmploye` ASC) VISIBLE,
  CONSTRAINT `fk_Employe_has_Projet_Employe`
    FOREIGN KEY (`fk_idEmploye`)
    REFERENCES `mydb`.`Employe` (`idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employe_has_Projet_Projet1`
    FOREIGN KEY (`fk_idProjet`)
    REFERENCES `mydb`.`Projet` (`idProjet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localisation` (
  `fk_idPoste` INT NOT NULL,
  `fk_id_site` INT NOT NULL,
  PRIMARY KEY (`fk_idPoste`, `fk_id_site`),
  INDEX `fk_Poste_has_Site_Site1_idx` (`fk_id_site` ASC) VISIBLE,
  INDEX `fk_Poste_has_Site_Poste1_idx` (`fk_idPoste` ASC) VISIBLE,
  CONSTRAINT `fk_Poste_has_Site_Poste1`
    FOREIGN KEY (`fk_idPoste`)
    REFERENCES `mydb`.`Poste` (`idPoste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Poste_has_Site_Site1`
    FOREIGN KEY (`fk_id_site`)
    REFERENCES `mydb`.`Site` (`id_site`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
