-- MySQL Script generated by MySQL Workbench
-- Tue Feb 23 08:27:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Employe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employe` ;

CREATE TABLE IF NOT EXISTS `Employe` (
  `idEmploye` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `IdEntreprise` VARCHAR(45) NULL,
  `Tel` VARCHAR(45) NULL,
  `Adresse` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmploye`))
ENGINE = InnoDB
COMMENT = '\n';


-- -----------------------------------------------------
-- Table `Contrat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contrat` ;

CREATE TABLE IF NOT EXISTS `Contrat` (
  `idContrat` INT NOT NULL AUTO_INCREMENT,
  `CDI_CDD` VARCHAR(45) NULL,
  `Salaire` DECIMAL(2) NULL,
  `Employe_idEmploye` INT NOT NULL,
  PRIMARY KEY (`idContrat`, `Employe_idEmploye`),
  INDEX `fk_Contrat_Employe_idx` (`Employe_idEmploye` ASC),
  CONSTRAINT `fk_Contrat_Employe`
    FOREIGN KEY (`Employe_idEmploye`)
    REFERENCES `Employe` (`idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Poste`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Poste` ;

CREATE TABLE IF NOT EXISTS `Poste` (
  `idPoste` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(45) NULL,
  `Niveau_hierarchique` VARCHAR(45) NULL,
  `Employe_idEmploye` INT NOT NULL,
  PRIMARY KEY (`idPoste`, `Employe_idEmploye`),
  INDEX `fk_Poste_Employe1_idx` (`Employe_idEmploye` ASC),
  CONSTRAINT `fk_Poste_Employe1`
    FOREIGN KEY (`Employe_idEmploye`)
    REFERENCES `Employe` (`idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Site` ;

CREATE TABLE IF NOT EXISTS `Site` (
  `id_site` INT NOT NULL AUTO_INCREMENT,
  `Adresse` VARCHAR(45) NULL,
  `CP` VARCHAR(45) NULL,
  `Ville` VARCHAR(45) NULL,
  `Pays` VARCHAR(45) NULL,
  PRIMARY KEY (`id_site`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projet` ;

CREATE TABLE IF NOT EXISTS `Projet` (
  `idProjet` INT NOT NULL AUTO_INCREMENT,
  `Mission` VARCHAR(45) NULL,
  `Durée` DECIMAL NULL,
  `Cout` DECIMAL NULL,
  PRIMARY KEY (`idProjet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Poste_has_Site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Poste_has_Site` ;

CREATE TABLE IF NOT EXISTS `Poste_has_Site` (
  `Poste_idPoste` INT NOT NULL,
  `Poste_Employe_idEmploye` INT NOT NULL,
  `Site_id_site` INT NOT NULL,
  PRIMARY KEY (`Poste_idPoste`, `Poste_Employe_idEmploye`, `Site_id_site`),
  INDEX `fk_Poste_has_Site_Site1_idx` (`Site_id_site` ASC),
  INDEX `fk_Poste_has_Site_Poste1_idx` (`Poste_idPoste` ASC, `Poste_Employe_idEmploye` ASC),
  CONSTRAINT `fk_Poste_has_Site_Poste1`
    FOREIGN KEY (`Poste_idPoste` , `Poste_Employe_idEmploye`)
    REFERENCES `Poste` (`idPoste` , `Employe_idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Poste_has_Site_Site1`
    FOREIGN KEY (`Site_id_site`)
    REFERENCES `Site` (`id_site`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employe_has_Projet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employe_has_Projet` ;

CREATE TABLE IF NOT EXISTS `Employe_has_Projet` (
  `Employe_idEmploye` INT NOT NULL,
  `Projet_idProjet` INT NOT NULL,
  PRIMARY KEY (`Employe_idEmploye`, `Projet_idProjet`),
  INDEX `fk_Employe_has_Projet_Projet1_idx` (`Projet_idProjet` ASC),
  INDEX `fk_Employe_has_Projet_Employe1_idx` (`Employe_idEmploye` ASC),
  CONSTRAINT `fk_Employe_has_Projet_Employe1`
    FOREIGN KEY (`Employe_idEmploye`)
    REFERENCES `Employe` (`idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employe_has_Projet_Projet1`
    FOREIGN KEY (`Projet_idProjet`)
    REFERENCES `Projet` (`idProjet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
